version "4.10.0"

#include "zscript/CheelloVox/CheelloVoxHandler.zc"
#include "zscript/CheelloVox/CheelloBlood.zc"
#include "zscript/CheelloVox/CheelloRocketPlugin.zc"
//#include "zscript/CheelloVox/CheelloSphereShell.zc"
//#include "zscript/CheelloVox/CheelloPowerupsDoom1.zc"
#include "zscript/CheelloVox/CheelloMonstersDoom1.zc"

#include "zsc/fountain.zsc"
#include "zsc/teleporter_effects.zsc"

Const MRGP_MaxWounds = 15;//Max wounds per entity
Const MRGP_DistanceMult = 2.;//Effects scaling by distance
Const MRGP_GibbingTime = 60.;

enum MRGPartsSpawnFlags{
	MRSPF_SMOKE = 1,
}

Struct MRGParts
{
	Static Double Diff(Double a, Double b)
	{
		if(a>b)Return a-b;
		Return b-a;
	}
	
	Static Vector2 Vec2Mult(Vector2 Vec1, Vector2 Vec2)
	{
		Return (Vec1.X*Vec2.Y, Vec1.Y*Vec2.Y);
	}
	Static Vector2 Vec2Div(Vector2 Vec1, Vector2 Vec2)
	{
		Return (Vec1.X/Vec2.Y, Vec1.Y/Vec2.Y);
	}
	
	Static Vector3 Vec3Mult(Vector3 Vec1, Vector3 Vec2)
	{
		Return (Vec1.X*Vec2.Y, Vec1.Y*Vec2.Y, Vec1.Z*Vec2.Z);
	}
	Static Vector3 Vec3Div(Vector3 Vec1, Vector3 Vec2)
	{
		Return (Vec1.X/Vec2.Y, Vec1.Y/Vec2.Y, Vec1.Z/Vec2.Z);
	}
	
	Static Double VectorPitch(Vector3 Vec)
	{
		Return -atan2(Vec.Z, Vec.XY.Length());
	}
	
	Static Double AngleToVector2(Vector2 Pos, Vector2 Dir)
	{
		Vector2 Dif = Levellocals.Vec2Diff(Pos, Dir);
		
		Return VectorAngle(Dif.X, Dif.Y);
	}
	
	Static Double PitchToVector3(Vector3 Pos, Vector3 Dir)
	{
		Vector3 Dif = Levellocals.Vec3Diff(Pos, Dir);
		
		Return -atan2(Dif.Z, Dif.XY.Length());
	}
	
	Static Double Distance2D(Actor mo, Actor mo1)
	{
		if(!MRGoreParts_LiteDistance)Return mo.Distance2D(mo1);
		
		Vector2 Vec1, Vec2;
		
		Vec1 = mo.Pos.XY;
		Vec2 = mo1.Pos.XY;
		
		Vector2 Dif = Levellocals.Vec2Diff(Vec1, Vec2);
		
		Return Dif.Length();
	}
	Static Double Distance2DV(Vector2 Vec1, Vector2 Vec2)
	{
		Vector2 Dif = Levellocals.Vec2Diff(Vec1, Vec2);
		
		Return Dif.Length();
	}
	
	Static Double Distance3D(Actor mo, Actor mo1)
	{
		if(!MRGoreParts_LiteDistance)Return mo.Distance3D(mo1);
		
		Vector3 Vec1, Vec2;
		
		Vec1 = mo.Pos;
		Vec2 = mo1.Pos;
		
		Vector3 Dif = Levellocals.Vec3Diff(Vec1, Vec2);
		
		Return Dif.Length();
	}
	Static Double Distance3DV(Vector3 Vec1, Vector3 Vec2)
	{
		Vector3 Dif = Levellocals.Vec3Diff(Vec1, Vec2);
		
		Return Dif.Length();
	}
	
	Static Void SpawnParticle(Color Col=Color(0,0,0), int Flags=0, int Style=STYLE_None, int Life=1, double Size=1, double Angle=0, Vector3 Pos=(0,0,0), Vector3 Vel=(0,0,0), Vector3 Accel=(0,0,0), Double Alpha=1, Double Fade=0, Double SizeStep=0)
	{
		FSpawnParticleParams p;
		p.Accel = Accel;
		p.Vel = Vel;
		
		p.Pos = Pos;
		
		p.Color1 = Col;
		p.LifeTime = Life;
		p.size = Size;
		p.sizeStep = SizeStep;
		p.startalpha = Alpha;
		p.fadestep = Fade;
		
		int Glow = 0;
		if(MRGoreParts_FullBright)Glow = SPF_FULLBRIGHT;
		p.Flags = Glow|Flags;
		p.Style = Style;
		
		if(Flags&MRSPF_SMOKE){
			Switch(MRGoreParts_MistTexture)
			{
				Case 0:p.Texture = Texman.CheckForTexture("GParMst");Break;
				Default: p.Texture = Texman.CheckForTexture("GParMst"..MRGoreParts_MistTexture);Break;
				Case 3:p.Texture = Texman.CheckForTexture("glpart");Break;
			}
		}
		else p.Texture = PartTexture();
		Level.SpawnParticle(p);
	}
	
	Static TextureID PartTexture()
	{
		Switch(MRGoreParts_ParticlesTexture)
		{
			Case 1:Return Texman.CheckForTexture("GParMst");
			Case 2:Return Texman.CheckForTexture("glpart2");
			Case 3:Return Texman.CheckForTexture("GParMst2");
		}
		Return Texman.CheckForTexture("glpart");
	}
}

//#include "MRGoreParts-code/HandlerFuncs.zsc"
#include "MRGoreParts-code/Handler.zsc"
#include "MRGoreParts-code/Thinkers.zsc"
#include "MRGoreParts-code/Effects.zsc"
#include "MRGoreParts-code/Wounds.zsc"
#include "MRGoreParts-code/Menu.zsc"

#include "ca.ancilla-(DontOverrideMePls)/TooltipOptionMenu.zsc"
#include "ca.ancilla-(DontOverrideMePls)/Tooltips.zsc"

Const MRGPCommLine = "//";
Const MRGPCommStart = "/*";
Const MRGPCommEnd = "*/";

#include "zscript/Gore/Pools.zs"
#include "zscript/Gore/Gibs.zs"
#include "zscript/Gore/Droplets.zs"
#include "zscript/Gore/Squirts.zs"
#include "zscript/Gore/Ceiling.zs"
#include "zscript/Gore/Liquid.zs"
#include "zscript/Gore/Events.zs"
#include "zscript/Gore/FloorSplat.zs"
#include "zscript/Gore/Wall.zs"
#include "zscript/Gore/Mist.zs"
#include "zscript/Gore/Hideous.zs"

// global constants
const STAT_NashGore_Gore = Thinker.STAT_USER + 1;
const SLAUGHTERMAP_DIST = 1000.0;
const MAP_EPSILON = 1 / 65536.;

Class VerySimpleRainHandler : EventHandler
{
	Actor player;
	int randomcolor;
	int randomweather;
	int weatherchange;
	int raincolorchange;
	int randomactive;
	int randomrain;
	
	override void WorldLoaded(WorldEvent e){

		CVar.FindCVar("rottlightning").SetInt(0);
		CVar.FindCVar("rottindoors").SetInt(0);
		CVar.FindCVar("windchange").SetInt(0);
		CVar.FindCVar("weatherchange").SetInt(0);
		CVar.FindCVar("raincolorchange").SetInt(0);
		CVar.FindCVar("quakedelay").SetInt(0);
		CVar.FindCVar("indoordelay").SetInt(6);
		CVar.FindCVar("outdoordelay").SetInt(6);
		randomweather = 0;
		weatherchange = 0;
		randomcolor = 0;
		raincolorchange = 0;
		randomactive = 0;
		randomrain = 0;

	}
	
	override void WorldTick(){

		if(CVar.FindCVar("raincolor").GetInt() == 7 && raincolorchange <= 1000 && randomcolor == 1 && CVar.FindCVar("weatheractive").GetInt() == 0 && randomrain == 7){
			raincolorchange++;
		}else{
			if(CVar.FindCVar("raincolor").GetInt() == 7 && CVar.FindCVar("weatheractive").GetInt() == 0){
				CVar.FindCVar("rainrandom").SetInt(random(0,6));
				while(CVar.FindCVar("rainrandom").GetInt() == CVar.FindCVar("raincoloractive").GetInt()){
					CVar.FindCVar("rainrandom").SetInt(random(0,6));
					if(CVar.FindCVar("rainrandom").GetInt() != CVar.FindCVar("raincoloractive").GetInt()){
						CVar.FindCVar("raincoloractive").SetInt(CVar.FindCVar("rainrandom").GetInt());
						raincolorchange = 0;
						randomcolor = 1;
						randomrain = 7;
						break;
					}			
				}
			}
		}

		if(CVar.FindCVar("raincolor").GetInt() < 7){
			CVar.FindCVar("raincoloractive").SetInt(CVar.FindCVar("raincolor").GetInt());
			raincolorchange = 0;
			randomcolor = 0;
			randomrain = 0;
		}

		if(CVar.FindCVar("raincolor").GetInt() == 8 && CVar.FindCVar("weatheractive").GetInt() == 0 && randomrain != 8){
			CVar.FindCVar("rainrandom").SetInt(random(0,6));
			while(CVar.FindCVar("rainrandom").GetInt() == CVar.FindCVar("raincoloractive").GetInt()){
				CVar.FindCVar("rainrandom").SetInt(random(0,6));
				if(CVar.FindCVar("rainrandom").GetInt() != CVar.FindCVar("raincoloractive").GetInt()){
					CVar.FindCVar("raincoloractive").SetInt(CVar.FindCVar("rainrandom").GetInt());
					if(CVar.FindCVar("weatheractive").GetInt() == 0){
						raincolorchange = 0;
						randomcolor = 1;
						randomrain = 8;
					}
					break;
				}			
			}
		}

		if(CVar.FindCVar("weathermode").GetInt() == 3 && weatherchange <= 3000 && randomweather == 1 && randomactive == 3){
			if(CVar.FindCVar("weathermode").GetInt() == 3){
				weatherchange++;
			}
		}else{
			if(CVar.FindCVar("weathermode").GetInt() == 3){
				CVar.FindCVar("weatherrandom").SetInt(random(0,2));
				while(CVar.FindCVar("weatherrandom").GetInt() == CVar.FindCVar("weatheractive").GetInt()){
					CVar.FindCVar("weatherrandom").SetInt(random(0,2));
					if(CVar.FindCVar("weatherrandom").GetInt() != CVar.FindCVar("weatheractive").GetInt()){
						CVar.FindCVar("weatheractive").SetInt(CVar.FindCVar("weatherrandom").GetInt());
						weatherchange = 0;
						randomweather = 1;
						randomactive = 3;
						if(CVar.FindCVar("weatheractive").GetInt() == 0){
							raincolorchange = 0;
							randomcolor = 0;
							randomrain = 0;
						}
						break;
					}			
				}
			}
		}

		if(CVar.FindCVar("weathermode").GetInt() < 3){
			if((CVar.FindCVar("weathermode").GetInt() != CVar.FindCVar("weatheractive").GetInt() || weatherchange != 0) && CVar.FindCVar("weathermode").GetInt() == 0){
				raincolorchange = 0;
				randomcolor = 0;
			}
			CVar.FindCVar("weatheractive").SetInt(CVar.FindCVar("weathermode").GetInt());
			randomweather = 0;
			weatherchange = 0;
			randomactive = 0;
		}

		if(CVar.FindCVar("weathermode").GetInt() == 4 && randomactive != 4){
			CVar.FindCVar("weatherrandom").SetInt(random(0,2));
			while(CVar.FindCVar("weatherrandom").GetInt() == CVar.FindCVar("weatheractive").GetInt()){
				CVar.FindCVar("weatherrandom").SetInt(random(0,2));
				if(CVar.FindCVar("weatherrandom").GetInt() != CVar.FindCVar("weatheractive").GetInt()){
					CVar.FindCVar("weatheractive").SetInt(CVar.FindCVar("weatherrandom").GetInt());
					weatherchange = 0;
					randomweather = 1;
					randomactive = 4;
					if(CVar.FindCVar("weatheractive").GetInt() == 0){
						raincolorchange = 0;
						randomcolor = 0;
						randomrain = 0;
					}
					break;
				}			
			}
		}

		if((CVar.FindCVar("weathermode").GetInt() == 1 || CVar.FindCVar("weathermode").GetInt() == 2) || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatheractive").GetInt() >= 1)){
			CVar.FindCVar("windchange").SetInt(CVar.FindCVar("windchange").GetInt()+random(1,3));
			if(CVar.FindCVar("windchange").GetInt() >= 20000){
				CVar.FindCVar("windchange").SetInt(0);
			}
		}

		if(CVar.FindCVar("quakeactive").GetInt() == 1 || ((random(1,300) > 299 || CVar.FindCVar("quakedelay").GetInt() != 0) && CVar.FindCVar("quakeactive").GetInt() == 2 && CVar.FindCVar("quakedelay").GetInt() <= 1000)){
			if(CVar.FindCVar("quakeactive").GetInt() == 2 && CVar.FindCVar("quakedelay").GetInt() >= random(300,600)){
				CVar.FindCVar("quakedelay").SetInt(0);
			}else if(CVar.FindCVar("quakeactive").GetInt() == 2){
				CVar.FindCVar("quakedelay").SetInt(CVar.FindCVar("quakedelay").GetInt()+1);
			}
		}
		if(CVar.FindCVar("quakeactive").GetInt() == 0 && CVar.FindCVar("quakedelay").GetInt() != 0){
			CVar.FindCVar("quakedelay").SetInt(0);
		}
	}

	override void PlayerEntered(PlayerEvent e) {
		self.player = players[consoleplayer].mo;
		self.player.giveinventory("VerySimpleRainItem", 1);
	}
}

class VerySimpleRainItem : CustomInventory {
	RainSound SelfSound;
	RainSpawner SelfRain1;
	RainSpawner SelfRain2;
	RainSpawner SelfRain3;
	RainSpawner SelfRain4;
	RainSpawner SelfRain5;
	RainSpawner SelfRain6;
	RainSpawner SelfRain7;
	RainSpawner SelfRain8;
	RainSpawner SelfRain9;
	bool Active;
	int worldLoaded;

	default{
		Inventory.AltHUDIcon "UMBRA0";
		Inventory.MaxAmount 1;
		-INVENTORY.INVBAR
		-INVENTORY.AUTOACTIVATE
		+INVENTORY.PERSISTENTPOWER
		+INVENTORY.UNDROPPABLE
	}

	override void DoEffect() {
		super.DoEffect();

		if(CVar.FindCVar("rainactive").GetInt()){
			active = true;
		}else{
			active = false;
		}
		if(!SelfSound && worldLoaded == 3) { worldLoaded = 0; }

		if(Active && Level.Mapname != "TITLEMAP") {
			if(SelfRain1) { SelfRain1.Destroy(); }
			if(SelfRain2) { SelfRain2.Destroy(); }
			if(SelfRain3) { SelfRain3.Destroy(); }
			if(SelfRain4) { SelfRain4.Destroy(); }
			if(SelfRain5) { SelfRain5.Destroy(); }
			if(SelfRain6) { SelfRain6.Destroy(); }
			if(SelfRain7) { SelfRain7.Destroy(); }
			if(SelfRain8) { SelfRain8.Destroy(); }
			if(SelfRain9) { SelfRain9.Destroy(); }

			Vector3 a = (owner.pos.x,owner.pos.y,GetZAt(owner.pos.x,owner.pos.y,GZF_CEILING));
			Vector3 b = (owner.pos.x,owner.pos.y,owner.pos.z);

			if(!SelfSound && worldLoaded == 1){
				SelfSound = RainSound(Spawn("RainSound",b,false));
				SelfSound.FollowTarget = owner;
				worldLoaded = 3;
			}

			if(worldLoaded < 2){
				worldLoaded = 1;
			}

			SelfRain1 = RainSpawner(Spawn("RainSpawner",a,false));
			SelfRain1.FollowTarget = owner;
			SelfRain2 = RainSpawner(Spawn("RainSpawner",a,false));
			SelfRain2.FollowTarget = owner;
			SelfRain3 = RainSpawner(Spawn("RainSpawner",a,false));
			SelfRain3.FollowTarget = owner;

			if(CVar.FindCVar("rainintensity").GetInt() >= 1){
				SelfRain4 = RainSpawner(Spawn("RainSpawner",a,false));
				SelfRain4.FollowTarget = owner;
				SelfRain5 = RainSpawner(Spawn("RainSpawner",a,false));
				SelfRain5.FollowTarget = owner;
				SelfRain6 = RainSpawner(Spawn("RainSpawner",a,false));
				SelfRain6.FollowTarget = owner;				
			}

			if(CVar.FindCVar("rainintensity").GetInt() >= 2){
				SelfRain7 = RainSpawner(Spawn("RainSpawner",a,false));
				SelfRain7.FollowTarget = owner;
				SelfRain8 = RainSpawner(Spawn("RainSpawner",a,false));
				SelfRain8.FollowTarget = owner;
				SelfRain9 = RainSpawner(Spawn("RainSpawner",a,false));
				SelfRain9.FollowTarget = owner;
			}

		}
		else {
			if(SelfSound) { SelfSound.Destroy(); }
			if(SelfRain1) { SelfRain1.Destroy(); }
			if(SelfRain2) { SelfRain2.Destroy(); }
			if(SelfRain3) { SelfRain3.Destroy(); }
			if(SelfRain4) { SelfRain4.Destroy(); }
			if(SelfRain5) { SelfRain5.Destroy(); }
			if(SelfRain6) { SelfRain6.Destroy(); }
			if(SelfRain7) { SelfRain7.Destroy(); }
			if(SelfRain8) { SelfRain8.Destroy(); }
			if(SelfRain9) { SelfRain9.Destroy(); }
			worldLoaded = 0;
		}

	}

	States {
	Spawn:
		TNT1 A 0;
		UMBR A -1;
		Loop;
	Use:
		TNT1 A 1 ToggleActive();
		Loop;
	}

	action void ToggleActive() {
		if(CVar.FindCVar("rainactive").GetInt()){
			console.printf("RAIN OFF");
			CVar.FindCVar("rainactive").SetInt(0);
		}else{
			console.printf("RAIN ON");
			CVar.FindCVar("rainactive").SetInt(1);
		}
	}


}

class RainSpawner : Actor
{
	actor FollowTarget;
	int randomX;
	int randomY;
	int randomZ;
	PreSpawnerRottSFX SelfRottSFX;

	default{
		Radius 1;
		Height 1;
		+NoClip;
		+ClientSideOnly;
		+SpawnCeiling;
		+NoGravity;
	}

    override void Tick() {
        super.Tick();

		Vector3 a = (followtarget.pos.x,followtarget.pos.y,GetZAt(followtarget.pos.x,followtarget.pos.y,GZF_CEILING));
		SetOrigin(
            a,
            true);
    }

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 {
			randomX = Random(-512,512);
			randomY = Random(-512,512);
			A_SpawnItemEx("PreSpawner", randomX, randomY, GetZAt(randomX,randomY), 0, 0, 0, 0 , 128, 0);
			randomX = Random(-512,512);
			randomY = Random(-512,512);
			A_SpawnItemEx("PreSpawner", randomX, randomY, GetZAt(randomX,randomY), 0, 0, 0, 0 , 128, 0);
			if(CVar.FindCVar("rainintensity").GetInt() >= 1){
				randomX = Random(-512,512);
				randomY = Random(-512,512);
				A_SpawnItemEx("PreSpawner", randomX, randomY, GetZAt(randomX,randomY), 0, 0, 0, 0 , 128, 0);
				randomX = Random(-512,512);
				randomY = Random(-512,512);
				A_SpawnItemEx("PreSpawner", randomX, randomY, GetZAt(randomX,randomY), 0, 0, 0, 0 , 128, 0);
			}
			if(CVar.FindCVar("rainintensity").GetInt() >= 2){
				randomX = Random(-512,512);
				randomY = Random(-512,512);
				A_SpawnItemEx("PreSpawner", randomX, randomY, GetZAt(randomX,randomY), 0, 0, 0, 0 , 128, 0);
				randomX = Random(-512,512);
				randomY = Random(-512,512);
				A_SpawnItemEx("PreSpawner", randomX, randomY, GetZAt(randomX,randomY), 0, 0, 0, 0 , 128, 0);
			}
			randomX = Random(Random(-512,-1024),Random(512,1024));
			randomY = Random(Random(-512,-1024),Random(512,1024));
			A_SpawnItemEx("PreSpawner", randomX, randomY, GetZAt(randomX,randomY), 0, 0, 0, 0 , 128, 0);
			randomX = Random(-512,512);
			randomY = Random(-512,512);
			Vector3 b = (self.pos.x+randomX,self.pos.y+randomY,GetZAt(self.pos.x+randomX,self.pos.y+randomY));
			if(!SelfRottSFX && CVar.FindCVar("rottsfx").GetInt()){
				SelfRottSFX = PreSpawnerRottSFX(Spawn("PreSpawnerRottSFX",b,false));
			}
			if(CVar.FindCVar("quakeactive").GetInt() == 1 || (CVar.FindCVar("quakeactive").GetInt() == 2 && CVar.FindCVar("quakedelay").GetInt() != 0)){
				int z = random(0,2);
				if(z == 0){
					A_QuakeEx(random(1,2), random(1,2), random(1,2), 35, 0, 3000,"");
				}
				if(z == 1){
					A_QuakeEx(random(2,4), random(2,4), random(2,4), 35, 0, 3000,"");
				}
				if(z == 2){
					A_QuakeEx(random(4,8), random(4,8), random(4,8), 35, 0, 3000,"");
				}
			}
		}
		TNT1 A 1;
		Loop;
	}
}

class PreSpawnerRottSFX : PreSpawner
{
	default{
		Radius 1;
		Height 1;
		+NoClip;
		+ClientSideOnly;
		+SpawnCeiling;
		+NoGravity;
	}

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(!self.CurSector,"Nothing");
		TNT1 A 0 {
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			ceilingHeight = self.curSector.ceilingplane.ZatPoint(spawnSpot);
		}
		TNT1 A 1 A_SpawnItemEx("RottSFX", 0, 0, (ceilingHeight-self.pos.z)-2, 0, 0, 0, 0 , 128, 0);
		Goto Nothing;
	}
}

class RainBase : Actor
{
	protected bool, double CheckSky(Sector sec, Vector2 spot, double z)
	{
		bool sky;
		double ceilz;
		
		if (!sec)
			return sky, ceilz;
		
		Sector ceilSec;
		[ceilz, ceilSec] = sec.HighestCeilingAt(spot);
		if (ceilSec.GetTexture(Sector.ceiling) == skyflatnum)
		{
			double top = sec.NextHighestCeilingAt(spot.x, spot.y, z, z+1);
			if (top == ceilz)
				sky = true;
		}
		
		return sky, ceilz;
	}

	States
	{
	Nothing:
		TNT1 A 0;
		TNT1 A 0 {
			Destroy();
		}
		Stop;
	}
}

class RottSFX : RainBase
{
	actor player;
	Vector2 spawnSpot;
	Vector2 playerSpot;
	bool skyCheck;
	double ceilz;
	bool skyCheckPlayer;
	double ceilzPlayer;
	int randomSFX;
	int rottlightning;
	int delay;
	Vector3 x;
	int gotSight;

	default{
		Radius 512;
		Height 1;
		-NoClip;
		+ClientSideOnly;
		+SpawnCeiling;
		+NoGravity;
	}

    override void Tick() {
        super.Tick();

		self.player = players[consoleplayer].mo;
		playerSpot = self.player.Vec2Offset(self.player.pos.x, self.player.pos.y);
		[skyCheckPlayer, ceilzPlayer] = CheckSky(self.player.CurSector, playerSpot, self.player.curSector.ceilingplane.ZatPoint(playerSpot));

		if(skyCheckPlayer && CVar.FindCVar("rottindoors").GetInt() > 0){
			skyCheckPlayer = false;
		}
    }

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 {
			delay = 3000;
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			[skyCheck, ceilz] = CheckSky(self.CurSector, spawnSpot, self.curSector.ceilingplane.ZatPoint(spawnSpot));
			if(skyCheck && ceilz > ceilingz){
				skyCheck = false;
			}
		}
		TNT1 A 0 A_JumpIf(random(1,100)>69||CVar.FindCVar("weatheractive").GetInt() != 0,"Nothing");
		TNT1 A 3;
		TNT1 A 0 {
			randomSFX = random(1,delay);
			if(((randomSFX > delay-3 && CVar.FindCVar("rottfrequency").GetInt() == 0) ||
				(randomSFX > delay-6 && CVar.FindCVar("rottfrequency").GetInt() == 1) ||
					(randomSFX > delay-9 && CVar.FindCVar("rottfrequency").GetInt() == 2)) && !CVar.FindCVar("rottlightning").GetInt()){
				if((CVar.FindCVar("rottindoors").GetInt() >= delay*0.009 && CVar.FindCVar("rottfrequency").GetInt() == 0 && !skyCheckPlayer)||
					(CVar.FindCVar("rottindoors").GetInt() >= delay*0.006 && CVar.FindCVar("rottfrequency").GetInt() == 1 && !skyCheckPlayer)||
						(CVar.FindCVar("rottindoors").GetInt() >= delay*0.003 && CVar.FindCVar("rottfrequency").GetInt() == 2 && !skyCheckPlayer)){
					CVar.FindCVar("rottindoors").SetInt(0);
					return A_Jump(256,"ThunderIndoors");
				}
				return A_Jump(256,"Lightning");
			}
			return ResolveState("Check");
		}
		Goto Nothing;
	Check:
		TNT1 A 0;
		TNT1 A 0 {
			randomSFX = random(1,delay);
			if(((randomSFX > delay-3 && CVar.FindCVar("rottfrequency").GetInt() == 0)||(randomSFX > delay-6 && CVar.FindCVar("rottfrequency").GetInt() == 1)
				||(randomSFX > delay-9 && CVar.FindCVar("rottfrequency").GetInt() == 2)) && CVar.FindCVar("rottlightning").GetInt()){
				CVar.FindCVar("rottlightning").SetInt(0);
				return A_Jump(256,"Thunder");			
			}
			return A_Jump(256,"Nothing");
		}
		Goto Nothing;
	Thunder:
		TNT1 A 0 A_JumpIf(!skyCheckPlayer && (!CVar.FindCVar("outdoordelay").GetInt() || !CVar.FindCVar("audiodelay").GetInt()),"ThunderIndoors");
		TNT1 A 1 {
			if(CVar.FindCVar("audiolevel").GetInt() == 2){
				A_PlaySound("rott/thunder",5|64|4096,1.0,false,ATTN_NONE);
			}
			if(CVar.FindCVar("audiolevel").GetInt() == 1){
				A_PlaySound("rott/thunderlower",5|64|4096,1.0,false,ATTN_NONE);
			}
			if(CVar.FindCVar("audiolevel").GetInt() == 0){
				A_PlaySound("rott/thunderevenlower",5|64|4096,1.0,false,ATTN_NONE);
			}
		}
		Goto Nothing;
	ThunderIndoors:
		TNT1 A 1 {
			if(CVar.FindCVar("audiolevel").GetInt() == 2){
				A_PlaySound("rott/thunderlower",5|64|4096,1.0,false,ATTN_NONE);
			}
			if(CVar.FindCVar("audiolevel").GetInt() == 1){
				A_PlaySound("rott/thunderevenlower",5|64|4096,1.0,false,ATTN_NONE);
			}
			if(CVar.FindCVar("audiolevel").GetInt() == 0){
				A_PlaySound("rott/thunderveryquiet",5|64|4096,1.0,false,ATTN_NONE);
			}
		}
		Goto Nothing;
	Lightning:
		TNT1 A 0 A_JumpIf(!skyCheck,"NoLightning");		
		TNT1 A 0 {
			gotSight = 0;
			if(!CheckSight(self.player) || self.pos.z-self.player.pos.z > 512){
				float oldPos = self.pos.z;

				for(float z = self.pos.z;z--;z == floorz){

					if(self.pos.z < floorz){
						break;
					}

					x = (self.pos.x,self.pos.y,self.pos.z-1);
					SetXYZ(x);

					if(CheckSight(self.player) && self.pos.z <= self.player.ceilingz && self.pos.z-self.player.pos.z < 512){
						gotSight = 1;
						break;
					}

				}
			}else{
				gotSight = 1;
			}
		}
		TNT1 A 0 A_JumpIf(!gotSight,"NoLightning");
		TNT1 A 0 {
			CVar.FindCVar("rottlightning").SetInt(1);
			CVar.FindCVar("rottindoors").SetInt(0);
		}
		TNT1 A 0 A_Jump(256,"Lightning1","Lightning2","Lightning3");
		Goto Nothing;
	Lightning1:
		RSFX A random(12,15);
		Goto Nothing;
	Lightning2:
		RSFX B random(12,15);
		Goto Nothing;
	Lightning3:
		RSFX C random(12,15);
		Goto Nothing;
	NoLightning:
		TNT1 A 0 {
			CVar.FindCVar("rottindoors").SetInt(CVar.FindCVar("rottindoors").GetInt()+1);
		}
		Goto Nothing;
	}
}

class RainSound : RainBase
{
	actor FollowTarget;
	Vector2 spawnSpot;
	bool skyCheck;
	double ceilz;
	int rainIntensity;
	int weather;
	actor player;

	default{
		Radius 1;
		Height 1;
		+NoClip;
		+ClientSideOnly;
		-SpawnCeiling;
		-NoGravity;
	}

	override void Tick() {
		super.Tick();

		rainIntensity = CVar.FindCVar("rainintensity").GetInt();
		weather = CVar.FindCVar("weathermode").GetInt();

		Vector3 a = (followtarget.pos.x,followtarget.pos.y,followtarget.pos.z);
		SetOrigin(
			a,
			true);
	}

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 B 3;
		TNT1 A 0 {
			self.player = players[consoleplayer].mo;
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			[skyCheck, ceilz] = CheckSky(self.CurSector, spawnSpot, self.curSector.ceilingplane.ZatPoint(spawnSpot));

			if(skyCheck && ceilz > ceilingz){
				if(!CVar.FindCVar("rottindoors").GetInt()){
					CVar.FindCVar("rottindoors").SetInt(1);
				}
				skyCheck = false;
			}else if(skyCheck){
				CVar.FindCVar("rottindoors").SetInt(0);
			}
		}
		TNT1 A 0 A_JumpIf(CVar.FindCVar("audiolevel").GetInt() == -1,"Mute");
		TNT1 A 0 A_JumpIf(!skyCheck && rainIntensity == 0,"IndoorLow");
		TNT1 A 0 A_JumpIf(!skyCheck && rainIntensity == 1,"IndoorMedium");
		TNT1 A 0 A_JumpIf(!skyCheck && rainIntensity == 2,"IndoorHigh");
		TNT1 A 0 A_JumpIf(skyCheck && rainIntensity == 0,"Low");
		TNT1 A 0 A_JumpIf(skyCheck && rainIntensity == 1,"Medium");
		TNT1 A 0 A_JumpIf(skyCheck && rainIntensity == 2,"High");
		Loop;
	Low:
		TNT1 A 0 {
			if(CVar.FindCVar("audiodelay").GetInt()){
				CVar.FindCVar("indoordelay").SetInt(0);
				CVar.FindCVar("outdoordelay").SetInt(CVar.FindCVar("outdoordelay").GetInt()+1);	
				if(CVar.FindCVar("outdoordelay").GetInt()==9){
					CVar.FindCVar("outdoordelay").SetInt(0);
				}
			}
		}
		TNT1 A 0 A_JumpIf(CVar.FindCVar("outdoordelay").GetInt() >= 1 && CVar.FindCVar("audiodelay").GetInt(),"Spawn");
		TNT1 A 2 {
			if(CVar.FindCVar("weathermode").GetInt() == 0 || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatherrandom").GetInt() == 0)){
				A_PlaySound("weather/rainevenlower",7|64|256|4096,1.0,true,ATTN_NONE);
			}else if(CVar.FindCVar("weathermode").GetInt() == 1 || CVar.FindCVar("weathermode").GetInt() == 2 || (CVar.FindCVar("weathermode").GetInt() >= 3 && (CVar.FindCVar("weatherrandom").GetInt() == 1 || CVar.FindCVar("weatherrandom").GetInt() == 2))){
				A_PlaySound("weather/windevenlower",7|64|256|4096,1.0,true,ATTN_NONE);
			}
			if(CVar.FindCVar("quakeactive").GetInt() == 1 || CVar.FindCVar("quakedelay").GetInt() != 0){
				A_PlaySound("weather/quakeevenlower",6|64|256|4096,1.0,true,ATTN_NONE);
			}else{
				A_StopSound(6);
			}
		}
		Goto Spawn;
	Medium:
		TNT1 A 0 A_JumpIf(CVar.FindCVar("audiolevel").GetInt() == 0,"Low");
		TNT1 A 0 {
			if(CVar.FindCVar("audiodelay").GetInt()){
				CVar.FindCVar("indoordelay").SetInt(0);
				CVar.FindCVar("outdoordelay").SetInt(CVar.FindCVar("outdoordelay").GetInt()+1);	
				if(CVar.FindCVar("outdoordelay").GetInt()==9){
					CVar.FindCVar("outdoordelay").SetInt(0);
				}
			}
		}
		TNT1 A 0 A_JumpIf(CVar.FindCVar("outdoordelay").GetInt() >= 1 && CVar.FindCVar("audiodelay").GetInt(),"Spawn");
		TNT1 A 2 {
			if(CVar.FindCVar("weathermode").GetInt() == 0 || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatherrandom").GetInt() == 0)){
				A_PlaySound("weather/rainlower",7|64|256|4096,1.0,true,ATTN_NONE);
			}else if(CVar.FindCVar("weathermode").GetInt() == 1 || CVar.FindCVar("weathermode").GetInt() == 2 || (CVar.FindCVar("weathermode").GetInt() >= 3 && (CVar.FindCVar("weatherrandom").GetInt() == 1 || CVar.FindCVar("weatherrandom").GetInt() == 2))){
				A_PlaySound("weather/windlower",7|64|256|4096,1.0,true,ATTN_NONE);
			}
			if(CVar.FindCVar("quakeactive").GetInt() == 1 || CVar.FindCVar("quakedelay").GetInt() != 0){
				A_PlaySound("weather/quakelower",6|64|256|4096,1.0,true,ATTN_NONE);
			}else{
				A_StopSound(6);
			}
			
		}
		Goto Spawn;
	High:
		TNT1 A 0 A_JumpIf(CVar.FindCVar("audiolevel").GetInt() == 1,"Medium");
		TNT1 A 0 A_JumpIf(CVar.FindCVar("audiolevel").GetInt() == 0,"Low");
		TNT1 A 0 {
			if(CVar.FindCVar("audiodelay").GetInt()){
				CVar.FindCVar("indoordelay").SetInt(0);
				CVar.FindCVar("outdoordelay").SetInt(CVar.FindCVar("outdoordelay").GetInt()+1);	
				if(CVar.FindCVar("outdoordelay").GetInt()==9){
					CVar.FindCVar("outdoordelay").SetInt(0);
				}
			}
		}
		TNT1 A 0 A_JumpIf(CVar.FindCVar("outdoordelay").GetInt() >= 1 && CVar.FindCVar("audiodelay").GetInt(),"Spawn");
		TNT1 A 2 {
			if(CVar.FindCVar("weathermode").GetInt() == 0 || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatherrandom").GetInt() == 0)){
				A_PlaySound("weather/rain",7|64|256|4096,1.0,true,ATTN_NONE);
			}else if(CVar.FindCVar("weathermode").GetInt() == 1 || CVar.FindCVar("weathermode").GetInt() == 2 || (CVar.FindCVar("weathermode").GetInt() >= 3 && (CVar.FindCVar("weatherrandom").GetInt() == 1 || CVar.FindCVar("weatherrandom").GetInt() == 2))){
				A_PlaySound("weather/wind",7|64|256|4096,1.0,true,ATTN_NONE);
			}
			if(CVar.FindCVar("quakeactive").GetInt() == 1 || CVar.FindCVar("quakedelay").GetInt() != 0){
				A_PlaySound("weather/quake",6|64|256|4096,1.0,true,ATTN_NONE);
			}else{
				A_StopSound(6);
			}
		}
		Goto Spawn;
	IndoorLow:
		TNT1 A 0 {
			if(CVar.FindCVar("audiodelay").GetInt()){
				CVar.FindCVar("outdoordelay").SetInt(0);
				CVar.FindCVar("indoordelay").SetInt(CVar.FindCVar("indoordelay").GetInt()+1);	
				if(CVar.FindCVar("indoordelay").GetInt()==9){
					CVar.FindCVar("indoordelay").SetInt(0);
				}
			}
		}
		TNT1 A 0 A_JumpIf(CVar.FindCVar("indoordelay").GetInt() >= 1 && CVar.FindCVar("audiodelay").GetInt(),"Spawn");
		TNT1 A 2 {
			if(CVar.FindCVar("weathermode").GetInt() == 0 || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatherrandom").GetInt() == 0)){
				A_PlaySound("weather/rainveryquiet",7|64|256|4096,1.0,true,ATTN_NONE);
			}else if(CVar.FindCVar("weathermode").GetInt() == 1 || CVar.FindCVar("weathermode").GetInt() == 2 || (CVar.FindCVar("weathermode").GetInt() >= 3 && (CVar.FindCVar("weatherrandom").GetInt() == 1 || CVar.FindCVar("weatherrandom").GetInt() == 2))){
				A_PlaySound("weather/windveryquiet",7|64|256|4096,1.0,true,ATTN_NONE);
			}
			if(CVar.FindCVar("quakeactive").GetInt() == 1 || CVar.FindCVar("quakedelay").GetInt() != 0){
				A_PlaySound("weather/quakeveryquiet",6|64|256|4096,1.0,true,ATTN_NONE);
			}else{
				A_StopSound(6);
			}
		}
		Goto Spawn;
	IndoorMedium:
		TNT1 A 0 A_JumpIf(CVar.FindCVar("audiolevel").GetInt() == 0,"IndoorLow");
		TNT1 A 0 {
			if(CVar.FindCVar("audiodelay").GetInt()){
				CVar.FindCVar("outdoordelay").SetInt(0);
				CVar.FindCVar("indoordelay").SetInt(CVar.FindCVar("indoordelay").GetInt()+1);	
				if(CVar.FindCVar("indoordelay").GetInt()==9){
					CVar.FindCVar("indoordelay").SetInt(0);
				}
			}
		}
		TNT1 A 0 A_JumpIf(CVar.FindCVar("indoordelay").GetInt() >= 1 && CVar.FindCVar("audiodelay").GetInt(),"Spawn");
		TNT1 A 2 {
			if(CVar.FindCVar("weathermode").GetInt() == 0 || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatherrandom").GetInt() == 0)){
				A_PlaySound("weather/rainevenlower",7|64|256|4096,1.0,true,ATTN_NONE);
			}else if(CVar.FindCVar("weathermode").GetInt() == 1 || CVar.FindCVar("weathermode").GetInt() == 2 || (CVar.FindCVar("weathermode").GetInt() >= 3 && (CVar.FindCVar("weatherrandom").GetInt() == 1 || CVar.FindCVar("weatherrandom").GetInt() == 2))){
				A_PlaySound("weather/windevenlower",7|64|256|4096,1.0,true,ATTN_NONE);
			}
			if(CVar.FindCVar("quakeactive").GetInt() == 1 || CVar.FindCVar("quakedelay").GetInt() != 0){
				A_PlaySound("weather/quakeevenlower",6|64|256|4096,1.0,true,ATTN_NONE);
			}else{
				A_StopSound(6);
			}
		}
		Goto Spawn;
	IndoorHigh:
		TNT1 A 0 A_JumpIf(CVar.FindCVar("audiolevel").GetInt() == 1,"IndoorMedium");
		TNT1 A 0 A_JumpIf(CVar.FindCVar("audiolevel").GetInt() == 0,"IndoorLow");
		TNT1 A 0 {
			if(CVar.FindCVar("audiodelay").GetInt()){
				CVar.FindCVar("outdoordelay").SetInt(0);
				CVar.FindCVar("indoordelay").SetInt(CVar.FindCVar("indoordelay").GetInt()+1);	
				if(CVar.FindCVar("indoordelay").GetInt()==9){
					CVar.FindCVar("indoordelay").SetInt(0);
				}
			}
		}
		TNT1 A 0 A_JumpIf(CVar.FindCVar("indoordelay").GetInt() >= 1 && CVar.FindCVar("audiodelay").GetInt(),"Spawn");
		TNT1 A 2 {
			if(CVar.FindCVar("weathermode").GetInt() == 0 || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatherrandom").GetInt() == 0)){
				A_PlaySound("weather/rainlower",7|64|256|4096,1.0,true,ATTN_NONE);
			}else if(CVar.FindCVar("weathermode").GetInt() == 1 || CVar.FindCVar("weathermode").GetInt() == 2 || (CVar.FindCVar("weathermode").GetInt() >= 3 && (CVar.FindCVar("weatherrandom").GetInt() == 1 || CVar.FindCVar("weatherrandom").GetInt() == 2))){
				A_PlaySound("weather/windlower",7|64|256|4096,1.0,true,ATTN_NONE);
			}
			if(CVar.FindCVar("quakeactive").GetInt() == 1 || CVar.FindCVar("quakedelay").GetInt() != 0){
				A_PlaySound("weather/quakelower",6|64|256|4096,1.0,true,ATTN_NONE);
			}else{
				A_StopSound(6);
			}
		}
		Goto Spawn;
	Mute:
		TNT1 A 0 {
			A_StopSound(6);
			A_StopSound(7);
		}
		Goto Spawn;
	}
}

class PreSpawner : RainBase
{
	Vector2 spawnSpot;
	int ceilingHeight;
	int floorHeight;
	int spawned;

	default{
		Radius 1;
		Height 1;
		+NoClip;
		+ClientSideOnly;
		+SpawnCeiling;
		+NoGravity;
	}

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(!self.CurSector,"Nothing");
		TNT1 A 0 {
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			ceilingHeight = self.curSector.ceilingplane.ZatPoint(spawnSpot);
			floorHeight = self.curSector.floorplane.ZatPoint(spawnSpot);
		}
		TNT1 A 1 {
			if(CVar.FindCVar("weathermode").GetInt() == 0 || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatheractive").GetInt() == 0)){
				A_SpawnItemEx("RainDrop", 0, 0, (ceilingHeight-self.pos.z)-2, 0, 0, frandom(-2,-9), 0 , 128, 0);
			}else if(CVar.FindCVar("weathermode").GetInt() == 1 || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatheractive").GetInt() == 1)){
				if(CVar.FindCVar("windchange").GetInt() <= 10000){
					A_SpawnItemEx("SnowBallRR", 0, 0, frandom((ceilingHeight-self.pos.z)-2,(ceilingz-floorz)*-1), random(2,8), -4, random(-2,0), 0 , 128, 0);
				}else{
					A_SpawnItemEx("SnowBallRR", 0, 0, frandom((ceilingHeight-self.pos.z)-2,(ceilingz-floorz)*-1), random(-2,-8), 4, random(-2,0), 0 , 128, 0);
				}
			}else if(CVar.FindCVar("weathermode").GetInt() == 2 || (CVar.FindCVar("weathermode").GetInt() >= 3 && CVar.FindCVar("weatheractive").GetInt() == 2)){
				if(CVar.FindCVar("windchange").GetInt() <= 10000){
					A_SpawnItemEx("AshesRR", 0, 0, frandom((ceilingHeight-self.pos.z)-2,(ceilingz-floorz)*-1), random(1,4), -2, random(-1,0), 0 , 128, 0);
				}else{
					A_SpawnItemEx("AshesRR", 0, 0, frandom((ceilingHeight-self.pos.z)-2,(ceilingz-floorz)*-1), random(-1,-4), 2, random(-1,0), 0 , 128, 0);
				}
			}
		}
		Goto Nothing;
	}
}

class RainDrop : RainBase
{
	Vector2 spawnSpot;
	Vector3 x;
	bool skyCheck;
	double ceilz;
	actor player;

	default {
		+Missile;
		+NoBlockMap;
		+DONTSPLASH;
		-NoGravity;
		-FLOORCLIP;
		Height 2;
		Radius 2;
		Renderstyle "Translucent";
		Alpha 0.0;
		Scale 0.25;
		VSpeed -69;	
		+FORCEYBILLBOARD;
		+VULNERABLE;
	}

	override void Tick() {
		super.Tick();

		if(WaterLevel > 0){
			alpha = 0.0;
			A_Die();
		}

    }

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			self.player = players[consoleplayer].mo;
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			[skyCheck, ceilz] = CheckSky(self.CurSector, spawnSpot, self.curSector.ceilingplane.ZatPoint(spawnSpot));
		}
		TNT1 A 0 A_JumpIf(!skyCheck,"Nothing");
		//TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(1024,"Nothing",1);
		TNT1 A 0 {
			if(random(1,1000) > 999){
				if(random(1,100) > 50){
					A_SpawnItemEx("HexenLeaves", 0, 0, 0, random(1,4), -2, random(-1,1), 0 , 128, 0);
				}else{
					A_SpawnItemEx("HexenLeaves", 0, 0, 0, random(-1,-4), 2, random(-1,1), 0 , 128, 0);
				}
			}
		}
		TNT1 A 0
		{
			bSPRITEFLIP = random(0,1);

			if(CVar.FindCVar("raincolor").GetInt() == 0 || (CVar.FindCVar("raincolor").GetInt() >= 7 && CVar.FindCVar("raincoloractive").GetInt() == 0)){
				A_SetTranslation("NormalRain");
			}
			if(CVar.FindCVar("raincolor").GetInt() == 1 || (CVar.FindCVar("raincolor").GetInt() >= 7 && CVar.FindCVar("raincoloractive").GetInt() == 1)){
				A_SetTranslation("RedRain");
			}
			if(CVar.FindCVar("raincolor").GetInt() == 2 || (CVar.FindCVar("raincolor").GetInt() >= 7 && CVar.FindCVar("raincoloractive").GetInt() == 2)){
				A_SetTranslation("GreenRain");			
			}
			if(CVar.FindCVar("raincolor").GetInt() == 3 || (CVar.FindCVar("raincolor").GetInt() >= 7 && CVar.FindCVar("raincoloractive").GetInt() == 3)){
				A_SetTranslation("BlueRain");				
			}
			if(CVar.FindCVar("raincolor").GetInt() == 4 || (CVar.FindCVar("raincolor").GetInt() >= 7 && CVar.FindCVar("raincoloractive").GetInt() == 4)){
				A_SetTranslation("BlackRain");
			}
			if(CVar.FindCVar("raincolor").GetInt() == 5 || (CVar.FindCVar("raincolor").GetInt() >= 7 && CVar.FindCVar("raincoloractive").GetInt() == 5)){
				A_SetTranslation("PurpleRain");
			}
			if(CVar.FindCVar("raincolor").GetInt() == 6 || (CVar.FindCVar("raincolor").GetInt() >= 7 && CVar.FindCVar("raincoloractive").GetInt() == 6)){
				if(random(0,1) == 0){
					A_SetTranslation("RedRain");
				}else{
					A_SetTranslation("BlueRain");
				}
			}

			alpha = frandom(0.0,0.3);

			scale.y = frandom(0.01,0.05);
			scale.x = frandom(0.15,0.25);
		}
		RAIN A 3;
		TNT1 A 0{
			scale.y = frandom(0.05,1.5);
		}
		RAIN A 6 A_FadeIn(0.05);
		TNT1 A 0{
			scale.y = frandom(0.05,2.5);
		}
		RAIN A 9 A_FadeIn(0.05);
		Goto RainLoop;
	RainLoop:
		RAIN A 6;
		Loop;
	Death:
		RAIN A 1;
		TNT1 A 0
		{
			if(!skyCheck){
				return;
			}
			if(self.CurSector.PlaneMoving(Sector.floor)){
				return;
			}
			String s = TexMan.GetName(self.curSector.GetTexture(Sector.floor));
			let t = GetFloorTerrain();
			if (t.IsLiquid && pos.z <= floorz)
			{
				if(self.curSector.GetHeightSec()){
					A_SpawnItemEx("RainSplash", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);

				}else{
					A_SpawnItemEx("RainSplash", 0, 0, abs(pos.z-floorz), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-floorz), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-floorz), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-floorz), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
				}
			}else if(s.Mid(0, s.Length()-1) == "NUKAGE" || s.Mid(0, s.Length()-1) == "FWATER" ||
				s.Mid(0, s.Length()-1) == "SWATER" || s.Mid(0, s.Length()-1) == "LAVA" || 
					s.Mid(0, s.Length()-1) == "BLOOD" || (s.Mid(0, s.Length()-2) == "SLIME" && s.Mid(5,2).ToInt(10) < 9) ||
						s.Mid(0,s.Length()-1) == "FLTWAWA" || s.Mid(0,s.Length()-1) == "FLTFLWW" || s.Mid(0,s.Length()-1) == "FLTLAVA" ||
							s.Mid(0,s.Length()-1) == "FLTHUH" || s.Mid(0,s.Length()-1) == "FLTSLUD" || (s.Mid(0, s.Length()-2) == "X_0" && s.Mid(3,2).ToInt(10) < 12) ||
								s.Mid(2,s.Length()-2) == "WATR" || s.Mid(3,s.Length()-1) == "WATR" || s.Mid(1,s.Length()-2) == "LAVA" || s.Mid(1,s.Length()-2) == "BLOOD" || s.Mid(1,s.Length()-1) == "BLOOD" ||
									s.Mid(1,s.Length()-3) == "LQ"){
				if(WaterLevel > 0 && self.curSector.GetHeightSec()){
					A_SpawnItemEx("RainSplash", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
				}else{
					A_SpawnItemEx("RainSplash", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
				}
			}else{
				if(WaterLevel > 0 && self.curSector.GetHeightSec()){
					A_SpawnItemEx("RainSplash", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, abs(pos.z-self.curSector.GetHeightSec().floorplane.ZatPoint(spawnSpot)), 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
				}else if(WaterLevel > 0){
					A_SpawnItemEx("RainSplash", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
					A_SpawnItemEx("RainRipple", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
				}
			}
		}
		TNT1 A 0 {
			scale = (0.2,0.2);
			bForceYBillboard = false;
			bForceXYBillboard = true;
		}
		RAIN BCDE 1 {
			if(skyCheck){
				A_FadeIn(0.1);
			}
		}
		Goto Nothing;
	}
}

class RainSplash : RainBase
{
	Vector3 x;
	
	default {
		+NoBlockMap;
		+DONTSPLASH;
		+NoGravity;
		-FLOORCLIP;
		Height 0;
		Radius 0;
		Renderstyle "Translucent";
		Alpha 0.2;
		Scale 0.25;
		+FORCEYBILLBOARD;
	}

	override void Tick() {
		super.Tick();

		if(WaterLevel > 0){
			//alpha = 0.0;
			x = (self.pos.x,self.pos.y,self.pos.z+1);
			SetOrigin(x,false);
		}

	}

	States
	{
	Spawn:
		TNT1 A 0
		{
			bSPRITEFLIP = random(0,1);
			alpha = frandom(0.2,0.5);
			scale = (0.2,0.2);
			bForceYBillboard = false;
			bForceXYBillboard = true;
		}
		RAIN BCDE 1 A_FadeIn(0.1);
		Goto Nothing;
	}
}

class RainRipple : RainBase
{
	Vector3 x;
	double z;

	default {
		+NoBlockMap;
		+DONTSPLASH;
		+NoGravity;
		-FLOORCLIP;
		Height 0;
		Radius 0;
		Renderstyle "Translucent";
		Alpha 0.3;
		Scale 0.1;
		+FORCEYBILLBOARD;
	}

	override void Tick() {
		super.Tick();

		if(WaterLevel > 0){
			alpha = 0.0;
			x = (self.pos.x,self.pos.y,self.pos.z+1);
			SetOrigin(x,false);
		}

	}

	States
	{
	Spawn:
		TNT1 A 0
		{
			bSPRITEFLIP = random(0,1);
			alpha = 0.3;
			z = frandom(0.05,0.1);
			scale = (z,z);
			bForceYBillboard = false;
			bForceXYBillboard = true;
		}
		RIPL A 3 A_FadeOut(0.01);
		TNT1 A 0 {
			alpha = 0.3;
			z = frandom(0.1,0.15);
			scale = (z,z);
		}
		RIPL A 3 A_FadeOut(0.02);
		TNT1 A 0 {
			alpha = 0.3;
			z = frandom(0.15,0.20);
			scale = (z,z);
		}
		RIPL A 3 A_FadeOut(0.03);
		Goto Nothing;
	}
}

class SnowBallRR : RainBase
{
	Vector2 spawnSpot;
	bool skyCheck;
	double ceilz;
	actor player;
	double x;

	default {
		+Missile;
		+NoBlockMap;
		+DONTSPLASH;
		+NoGravity;
		-FLOORCLIP;
		+NOTELEPORT
		+THRUACTORS
		BounceType "Heretic";
		Height 2;
		Radius 2;
		Renderstyle "Translucent";
		Alpha 0.0;
		Scale 0.25;
		//VSpeed -69;	
		+FORCEYBILLBOARD;
		+VULNERABLE;
	}

	override void Tick() {
		super.Tick();

		if(WaterLevel > 0){
			alpha = 0.0;
			A_Die();
		}

		if(self.pos.z == self.curSector.floorplane.ZatPoint(self.Vec2Offset(self.pos.x, self.pos.y))){
			A_Stop();
		}
    }

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			self.player = players[consoleplayer].mo;
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			[skyCheck, ceilz] = CheckSky(self.CurSector, spawnSpot, self.curSector.ceilingplane.ZatPoint(spawnSpot));
		}
		TNT1 A 0 A_JumpIf(!skyCheck,"Nothing");
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0 {
			if(random(1,100) < 69){
				if(CVar.FindCVar("windchange").GetInt() <= 10000){
					A_SpawnItemEx("LittleWhiteCloud", 0, 0, 0, random(1,4), -2, random(-1,0), 0 , 128, 0);
				}else{
					A_SpawnItemEx("LittleWhiteCloud", 0, 0, 0, random(-1,-4), 2, random(-1,0), 0 , 128, 0);
				}
			}
			if(random(1,1000) > 999){
				if(CVar.FindCVar("windchange").GetInt() <= 10000){
					A_SpawnItemEx("HexenLeaves", 0, 0, 0, random(1,4), -2, random(-1,1), 0 , 128, 0);
				}else{
					A_SpawnItemEx("HexenLeaves", 0, 0, 0, random(-1,-4), 2, random(-1,1), 0 , 128, 0);
				}
			}
		}
		TNT1 A 0
		{
			bSPRITEFLIP = random(0,1);
			//alpha = frandom(0.1,0.5);
			x = frandom(0.1,0.3);
			scale = (x,x);
		}
		SNOW A 3 A_FadeIn(0.1);
		SNOW A 6 A_FadeIn(0.2);
		SNOW A 9 A_FadeIn(0.3);
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		Goto Loopy;
	Loopy:
		SNOW A 6;
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0 A_Jump(32,"Death");
		TNT1 A 0 A_Jump(32,"SpiralLoop");
		Loop;
	SpiralLoop:
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		SNOW A 1 A_SetAngle(angle+random(10,30));
		SNOW A 1 A_ChangeVelocity (random(1.0,2.0), 0.0, -0.5, CVF_RELATIVE|CVF_REPLACE);
		TNT1 A 0 A_Jump(16,"Death");
		Loop;
	Death:
		SNOW A 9 {
			A_FadeOut(0.3);
			scale = (self.scale.x-0.05,self.scale.y-0.05);
		}
		Goto Nothing;
	}
}

class LittleWhiteCloud : RainBase
{
	Vector2 spawnSpot;
	bool skyCheck;
	double ceilz;
	actor player;
	double x;

	default {
		+Missile;
		+NoBlockMap;
		+DONTSPLASH;
		+NoGravity;
		-FLOORCLIP;
		+NOTELEPORT
		+THRUACTORS
		-BOUNCEONWALLS
		-BOUNCEONFLOORS
		-BOUNCEONCEILINGS
		Height 2;
		Radius 2;
		Renderstyle "Translucent";
		Alpha 0.0;
		Scale 0.1;
		//VSpeed -69;	
		+FORCEYBILLBOARD;
		+VULNERABLE;
		Translation "0:255=@75[255,255,255]";
	}

	override void Tick() {
		super.Tick();

		if(WaterLevel > 0){
			alpha = 0.0;
			A_Die();
		}

    }

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			self.player = players[consoleplayer].mo;
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			[skyCheck, ceilz] = CheckSky(self.CurSector, spawnSpot, self.curSector.ceilingplane.ZatPoint(spawnSpot));
		}
		TNT1 A 0 A_JumpIf(!skyCheck,"Nothing");
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0
		{
			bSPRITEFLIP = random(0,1);
			bXFLIP = random(0,1);
			bYFLIP = random(0,1);
			alpha = frandom(0.1,0.3);
			x = frandom(0.1,0.1);
			scale = (x,x);
		}
		RSMK ABCDE 5 A_FadeOut(0.05);
		Stop;
	}
}

class AshesRR : RainBase
{
	Vector2 spawnSpot;
	bool skyCheck;
	double ceilz;
	actor player;
	double x;

	default {
		+Missile;
		+NoBlockMap;
		+DONTSPLASH;
		+NoGravity;
		-FLOORCLIP;
		+NOTELEPORT
		+THRUACTORS
		BounceType "Heretic";
		Height 2;
		Radius 2;
		Renderstyle "Translucent";
		Alpha 0.0;
		Scale 0.25;
		//VSpeed -69;	
		+FORCEYBILLBOARD;
		+VULNERABLE;
		Translation "0:255=@50[0,0,0]";
	}

	override void Tick() {
		super.Tick();

		if(WaterLevel > 0){
			alpha = 0.0;
			A_Die();
		}

		if(self.pos.z == self.curSector.floorplane.ZatPoint(self.Vec2Offset(self.pos.x, self.pos.y))){
			A_Stop();
		}
    }

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			self.player = players[consoleplayer].mo;
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			[skyCheck, ceilz] = CheckSky(self.CurSector, spawnSpot, self.curSector.ceilingplane.ZatPoint(spawnSpot));
		}
		TNT1 A 0 A_JumpIf(!skyCheck,"Nothing");
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0 {
			if(random(1,100) > 99){
				if(CVar.FindCVar("windchange").GetInt() <= 10000){
					A_SpawnItemEx("EmbersRR", 0, 0, 0, random(1,4), -2, random(-1,0), 0 , 128, 0);
				}else{
					A_SpawnItemEx("EmbersRR", 0, 0, 0, random(-1,-4), 2, random(-1,0), 0 , 128, 0);
				}
			}
			if(random(1,1000) > 999){
				if(CVar.FindCVar("windchange").GetInt() <= 10000){
					A_SpawnItemEx("HexenLeaves", 0, 0, 0, random(1,4), -2, random(-1,1), 0 , 128, 0);
				}else{
					A_SpawnItemEx("HexenLeaves", 0, 0, 0, random(-1,-4), 2, random(-1,1), 0 , 128, 0);
				}
			}
		}
		TNT1 A 0
		{
			bSPRITEFLIP = random(0,1);
			bXFLIP = random(0,1);
			bYFLIP = random(0,1);
			//alpha = frandom(0.1,0.3);
			x = frandom(0.1,0.2);
			scale = (x,x);
		}
		ASH1 A 3 A_FadeIn(0.1);
		ASH1 A 6 A_FadeIn(0.2);
		ASH1 A 9 A_FadeIn(0.3);
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0 A_Jump(32,"Death");
		Goto Loopy;
	Loopy:
		ASH1 A 6;
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0 A_Jump(32,"Death");
		TNT1 A 0 A_Jump(32,"SpiralLoop");
		Loop;
	SpiralLoop:
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		ASH1 A 1 A_SetAngle(angle+random(10,-30));
		ASH1 A 1 A_ChangeVelocity (random(1.0,2.0), 0.0, -0.1, CVF_RELATIVE|CVF_REPLACE);
		TNT1 A 0 A_Jump(16,"Death");
		Loop;
	Death:
		ASH1 A 9 {
			A_FadeOut(0.3);
			scale = (self.scale.x-0.05,self.scale.y-0.05);
		}
		Goto Nothing;
	}
}

class EmbersRR : RainBase
{
	Vector2 spawnSpot;
	bool skyCheck;
	double ceilz;
	actor player;
	double x;

	default {
		+BRIGHT;
		+Missile;
		+NoBlockMap;
		+DONTSPLASH;
		+NoGravity;
		-FLOORCLIP;
		+NOTELEPORT
		+THRUACTORS
		+DONTBOUNCEONSKY
		+BOUNCEONWALLS
		-BOUNCEONFLOORS
		-BOUNCEONCEILINGS
		Height 2;
		Radius 2;
		Renderstyle "Translucent";
		Alpha 0.0;
		Scale 0.25;
		//VSpeed -69;	
		+FORCEYBILLBOARD;
		+VULNERABLE;
		Translation "0:255=@10[255,255,0]";
	}

	override void Tick() {
		super.Tick();

		if(WaterLevel > 0){
			alpha = 0.0;
			A_Die();
		}

    }

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			self.player = players[consoleplayer].mo;
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			[skyCheck, ceilz] = CheckSky(self.CurSector, spawnSpot, self.curSector.ceilingplane.ZatPoint(spawnSpot));
		}
		TNT1 A 0 A_JumpIf(!skyCheck,"Nothing");
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0
		{
			bSPRITEFLIP = random(0,1);
			bXFLIP = random(0,1);
			bYFLIP = random(0,1);
			//alpha = frandom(0.1,0.5);
			x = frandom(0.1,0.2);
			scale = (x,x);
		}
		ASH2 A 3 A_FadeIn(0.1);
		ASH2 A 6 A_FadeIn(0.2);
		ASH2 A 9 A_FadeIn(0.3);
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0 A_Jump(64,"Death");
		Goto SpiralLoop;
	Loopy:
		ASH2 A 3;
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0 A_Jump(32,"Death");
		TNT1 A 0 A_Jump(64,"SpiralLoop");
		Loop;
	SpiralLoop:
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		ASH1 A 1 A_SetAngle(angle+random(10,30));
		ASH2 A 1 A_ChangeVelocity (random(1.0,2.0), 0.0, -0.5, CVF_RELATIVE|CVF_REPLACE);
		//TNT1 A 0 A_Jump(4,"Death");
		Loop;
	Death:
		ASH2 A 9 {
			A_FadeOut(0.3);
			scale = (self.scale.x-0.05,self.scale.y-0.05);
		}
		Goto Nothing;
	}
}

class HexenLeaves : RainBase
{
	Vector2 spawnSpot;
	bool skyCheck;
	double ceilz;
	actor player;
	double x;

	default {
		+BRIGHT;
		+Missile;
		+NoBlockMap;
		+DONTSPLASH;
		+NoGravity;
		-FLOORCLIP;
		+NOTELEPORT
		+THRUACTORS
		+DONTBOUNCEONSKY
		+BOUNCEONWALLS
		-BOUNCEONFLOORS
		-BOUNCEONCEILINGS
		Height 2;
		Radius 2;
		Renderstyle "Translucent";
		Alpha 0.0;
		Scale 0.25;
		//VSpeed -69;	
		+FORCEYBILLBOARD;
		+VULNERABLE;
		//Translation "0:255=@10[255,255,0]";
	}

	override void Tick() {
		super.Tick();

		if(WaterLevel > 0){
			alpha = 0.0;
			A_Die();
		}

    }

	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			self.player = players[consoleplayer].mo;
			spawnSpot = self.Vec2Offset(self.pos.x, self.pos.y);
			[skyCheck, ceilz] = CheckSky(self.CurSector, spawnSpot, self.curSector.ceilingplane.ZatPoint(spawnSpot));
		}
		TNT1 A 0 A_JumpIf(!skyCheck,"Nothing");
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0
		{
			bSPRITEFLIP = random(0,1);
			bXFLIP = random(0,1);
			bYFLIP = random(0,1);
			//alpha = frandom(0.1,0.5);
			x = frandom(0.3,0.9);
			scale = (x,x);
		}
		TNT1 A 0 A_Jump(128,"Spawn2");
		LFH1 ABC 4;
		LFH1 D 4 A_FadeIn(0.1);
		LFH1 EFG 4;
		LFH1 H 4 A_FadeIn(0.2);
		LFH1 IAB 4;
		LFH1 C 4 A_FadeIn(0.3);
		LFH1 DEF 4;
		LFH1 G 4 A_FadeIn(0.4);
		LFH1 HI 4;
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		TNT1 A 0 A_Jump(64,"Death");
		Goto SpiralLoop;
	Spawn2:
		TNT1 A 0;
		LFH2 ABC 4;
		LFH2 D 4 A_FadeIn(0.1);
		LFH2 EFG 4;
		LFH2 H 4 A_FadeIn(0.2);
		LFH2 IAB 4;
		LFH2 C 4 A_FadeIn(0.3);
		LFH2 DEF 4;
		LFH2 G 4 A_FadeIn(0.4);
		LFH2 HI 4;
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		//TNT1 A 0 A_Jump(64,"Death");
		Goto SpiralLoop2;
	SpiralLoop:
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		LFH1 ABCD 4 A_SetAngle(angle+random(10,30));
		LFH1 EFGH 4 A_ChangeVelocity (random(1.0,2.0), 0.0, -0.5, CVF_RELATIVE|CVF_REPLACE);
		LFH1 I 1;
		Loop;
	SpiralLoop2:
		TNT1 A 0 A_CheckSight("Nothing");
		TNT1 A 0 A_CheckRange(512,"Nothing",0);
		LFH2 ABCD 4 A_SetAngle(angle+random(10,30));
		LFH2 EFGH 4 A_ChangeVelocity (random(1.0,2.0), 0.0, -0.5, CVF_RELATIVE|CVF_REPLACE);
		LFH2 I 1;
		Loop;
	Death:
		LFH3 ABCDE 10 {
			A_FadeOut(0.3);
			scale = (self.scale.x-0.05,self.scale.y-0.05);
		}
		Goto Nothing;
	}
}

const STAT_HDFLASH = Thinker.STAT_USER + 10;

#include "zscript/hd_relite_Events.zs"
#include "zscript/hd_shadowactors.zs"
#include "zscript/hd_lightactors.zs"
#include "zscript/hd_sector.zs"
#include "zscript/hd_math.zs"
#include "zscript/hd_mixin.zs"
#include "zscript/hd_postprocessor.zs"

#include "hd_initsprites.zs"
#include "hd_crosswalk.zs"

class DPWipeHandler : EventHandler
{
	PlayerInfo p ;
	int alive ;
	int WipeStart ;
	
	override void PlayerEntered( PlayerEvent e )
	{
		p = players[ consoleplayer ] ;
		alive = 1 ;
	}

	override void WorldTick()
	{
		if( p.mo.health <= 0 )
		{
			if( alive == 1 )
			{
				Shader.SetEnabled( p, "DPWipe", true );
				WipeStart = gametic ;
				alive = 0 ;
			}
			
			Shader.SetUniform1f( p, "DPWipe", "timer", ( gametic - WipeStart ) * 0.5 );
		}
		else
		{
			Shader.SetEnabled( p, "DPWipe", false );
			alive = 1 ;
		}
	}
}

Class TextureHotspot
{
	int xpos, ypos, r, g, b, radius, spotin, spotout;
	bool isspot;
}

Class LightTexture
{
	TextureID tex;
	Vector2 size;
	Array<TextureHotspot> hotspots;
}

Class LightTextureHandler : EventHandler
{
	Array<LightTexture> ltex;

	override void OnRegister()
	{
		ltex.Clear();
		int lmp;
		if ( (lmp = Wads.FindLump("LTEXDEFS")) == -1 ) return;
		String txt = Wads.ReadLump(lmp);
		Array<String> lines, cline;
		lines.Clear();
		txt.Split(lines,"\n",0);
		int nspots = 0;
		LightTexture ltx;
		TextureHotspot hs;
		for ( int i=0; i<lines.size(); i++ )
		{
			if ( (lines[i].CharAt(0) == "#")
				|| (lines[i].Length() <= 1) ) continue;
			cline.Clear();
			lines[i].Split(cline," ",0);
			if ( nspots )
			{
				if ( (cline.size() != 6) && (cline.size() != 8) )
				{
					Console.Printf("LTEXDEFS: line %d: expected 6 or 8 tokens, got %d.",i+1,cline.size());
					return;
				}
				hs = new("TextureHotspot");
				hs.xpos = cline[0].ToInt();
				hs.ypos = cline[1].ToInt();
				hs.r = cline[2].ToInt();
				hs.g = cline[3].ToInt();
				hs.b = cline[4].ToInt();
				hs.radius = cline[5].ToInt();
				if ( cline.size() == 8 )
				{
					hs.spotin = cline[6].ToInt();
					hs.spotout = cline[7].ToInt();
					hs.isspot = true;
				}
				else hs.isspot = false;
				ltx.hotspots.Push(hs);
				nspots--;
				continue;
			}
			if ( (cline.size() != 2) && (cline.size() != 3) )
			{
				Console.Printf("LTEXDEFS: line %d: expected 2 or 3 tokens, got %d.",i+1,cline.size());
				return;
			}
			ltx = new("LightTexture");
			if ( cline.size() == 2 )
			{
				ltx.tex = TexMan.CheckForTexture(cline[0],TexMan.Type_Any);
				nspots = cline[1].ToInt();
			}
			else
			{
				if ( cline[1] ~== "T" ) ltx.tex = TexMan.CheckForTexture(cline[0],TexMan.Type_Wall);
				else if ( cline[1] ~== "F" ) ltx.tex = TexMan.CheckForTexture(cline[0],TexMan.Type_Flat);
				else ltx.tex = TexMan.CheckForTexture(cline[0],TexMan.Type_Any);
				nspots = cline[2].ToInt();
			}
			ltx.size = TexMan.GetScaledSize(ltx.tex);
			ltx.hotspots.Clear();
			ltex.Push(ltx);
		}
		if ( nspots ) Console.Printf("LTEXDEFS: reached EOF when %d more hotspot definitions were expected",nspots);
	}

	void PopulateSideSection( Side s, int part, int h, Vector3 pos, Vector2 dir, Vector2 normal )
	{
		// check texture first
		let t = s.GetTexture(part);
		if ( !t.IsValid() || t.IsNull() ) return;
		int ltx = -1;
		for ( int i=0; i<ltex.Size(); i++ )
		{
			if ( ltex[i].tex != t ) continue;
			ltx = i;
			break;
		}
		if ( ltx == -1 ) return;
		int w = int((s.v2().p-s.v1().p).length());
		double xo, yo, xs, ys;
		int tw, th;
		xo = s.GetTextureXOffset(part);
		yo = s.GetTextureYOffset(part);
		xs = s.GetTextureXScale(part);
		ys = s.GetTextureYScale(part);
		// TODO properly handle pegged/unpegged flags
		// also TODO fix misalignment on upper textures
		tw = int(ltex[ltx].size.x);
		th = int(ltex[ltx].size.y);
		for ( int y=0; y<h; y++ ) for ( int x=0; x<w; x++ )
		{
			int ox = int((x+xo)*xs);
			int oy = int((y+yo)*ys);
			for ( int i=0; i<ltex[ltx].hotspots.Size(); i++ )
			{
				if ( (ox%tw == ltex[ltx].hotspots[i].xpos) && (oy%th == ltex[ltx].hotspots[i].ypos) )
				{
					if ( !level.IsPointInLevel(pos+(x*dir.x,x*dir.y,-y)+(normal.x*8.,normal.y*8.,0)) ) continue;
					let l = Actor.Spawn("PointLightAttenuated",pos+(x*dir.x,x*dir.y,-y)+(normal.x*8.,normal.y*8.,0));
					l.args[0] = ltex[ltx].hotspots[i].r;
					l.args[1] = ltex[ltx].hotspots[i].g;
					l.args[2] = ltex[ltx].hotspots[i].b;
					l.args[3] = ltex[ltx].hotspots[i].radius;
				}
			}
		}
	}

	void PopulateSectorPlane( Sector s, int part, Secplane plane )
	{
		// check texture first
		let t = s.GetTexture(part);
		if ( !t.IsValid() || t.IsNull() ) return;
		int ltx = -1;
		for ( int i=0; i<ltex.Size(); i++ )
		{
			if ( ltex[i].tex != t ) continue;
			ltx = i;
			break;
		}
		if ( ltx == -1 ) return;
		int sx = int.max, sy = int.max, ex = int.min, ey = int.min;
		// calc bounds
		for ( int i=0; i<s.lines.Size(); i++ )
		{
			if ( s.lines[i].v1.p.x < sx ) sx = int(s.lines[i].v1.p.x);
			if ( s.lines[i].v2.p.x < sx ) sx = int(s.lines[i].v2.p.x);
			if ( s.lines[i].v1.p.x > ex ) ex = int(s.lines[i].v1.p.x);
			if ( s.lines[i].v2.p.x > ex ) ex = int(s.lines[i].v2.p.x);
			if ( s.lines[i].v1.p.y < sy ) sy = int(s.lines[i].v1.p.y);
			if ( s.lines[i].v2.p.y < sy ) sy = int(s.lines[i].v2.p.y);
			if ( s.lines[i].v1.p.y > ey ) ey = int(s.lines[i].v1.p.y);
			if ( s.lines[i].v2.p.y > ey ) ey = int(s.lines[i].v2.p.y);
		}
		double xo, yo, xs, ys, ang;
		int tw, th;
		xo = s.GetXOffset(part);
		yo = s.GetYOffset(part);
		xs = s.GetXScale(part);
		ys = s.GetYScale(part);
		ang = s.GetAngle(part);	// TODO handle rotation
		tw = int(ltex[ltx].size.x);
		th = int(ltex[ltx].size.y);
		for ( int y=sy; y<ey; y++ ) for ( int x=sx; x<ex; x++ )
		{
			if ( level.PointInSector((x,y)) != s ) continue;
			int ox = int((x+xo)*xs);
			int oy = int((y+yo)*ys);
			if ( ox < 0 ) ox = tw-ox;
			if ( oy < 0 ) oy = th-oy;
			for ( int i=0; i<ltex[ltx].hotspots.Size(); i++ )
			{
				if ( (ox%tw == ltex[ltx].hotspots[i].xpos) && (oy%th == ltex[ltx].hotspots[i].ypos) )
				{
					if ( !level.IsPointInLevel((x,y,plane.ZAtPoint((x,y)))+plane.Normal*8.) ) continue;
					Actor l;
					if ( ltex[ltx].hotspots[i].isspot )
					{
						l = Actor.Spawn("SpotLightAttenuated",(x,y,plane.ZAtPoint((x,y)))+plane.Normal*8.);
						DynamicLight(l).SpotInnerAngle = ltex[ltx].hotspots[i].spotin;
						DynamicLight(l).SpotOuterAngle = ltex[ltx].hotspots[i].spotout;
						l.angle = atan2(plane.Normal.y,plane.Normal.x);
						l.pitch = asin(-plane.Normal.z);
					}
					else l = Actor.Spawn("PointLightAttenuated",(x,y,plane.ZAtPoint((x,y)))+plane.Normal*8.);
					l.args[0] = ltex[ltx].hotspots[i].r;
					l.args[1] = ltex[ltx].hotspots[i].g;
					l.args[2] = ltex[ltx].hotspots[i].b;
					l.args[3] = ltex[ltx].hotspots[i].radius;
				}
			}
		}
	}

	override void WorldLoaded( WorldEvent e )
	{
		if ( e.IsSaveGame || e.IsReopen ) return;
		for ( int i=0; i<level.Lines.Size(); i++ )
		{
			Line l = level.Lines[i];
			Vector2 n = (l.delta.y,-l.delta.x).unit();
			Vector3 p1, p2;
			p1.xy = l.v1.p;
			p2.xy = l.v2.p;
			if ( l.sidedef[1] )
			{
				// this part is a mess
				int c1, f1, c2, f2;
				c1 = int(l.frontsector.ceilingplane.ZAtPoint(l.v1.p));
				f1 = int(l.frontsector.floorplane.ZAtPoint(l.v1.p));
				c2 = int(l.backsector.ceilingplane.ZAtPoint(l.v1.p));
				f2 = int(l.backsector.floorplane.ZAtPoint(l.v1.p));
				// front upper
				p1.z = c1;
				if ( c1-c2 > 0 ) PopulateSideSection(l.sidedef[0],0,c1-c2,p1,l.delta.unit(),n);
				// front middle
				p1.z = c2;
				if ( c2-f2 > 0 ) PopulateSideSection(l.sidedef[0],1,c2-f2,p1,l.delta.unit(),n);
				// front bottom
				p1.z = f2;
				if ( f2-f1 > 0 ) PopulateSideSection(l.sidedef[0],2,f2-f1,p1,l.delta.unit(),n);
				// back upper
				p2.z = c2;
				if ( c2-c1 > 0 ) PopulateSideSection(l.sidedef[1],0,c2-c1,p2,-l.delta.unit(),-n);
				// back middle
				p2.z = c2;
				if ( c1-f1 > 0 ) PopulateSideSection(l.sidedef[1],1,c1-f1,p2,-l.delta.unit(),-n);
				// back bottom
				p2.z = f1;
				if ( f1-f2 > 0 ) PopulateSideSection(l.sidedef[1],2,f1-f2,p2,-l.delta.unit(),-n);
			}
			else
			{
				int c, f;
				c = int(l.frontsector.ceilingplane.ZAtPoint(l.v1.p));
				f = int(l.frontsector.floorplane.ZAtPoint(l.v1.p));
				p1.z = c;
				PopulateSideSection(l.sidedef[0],1,c-f,p1,l.delta.unit(),n);
			}
		}
		for ( int i=0; i<level.Sectors.Size(); i++ )
		{
			Sector s = level.Sectors[i];
			PopulateSectorPlane(s,0,s.floorplane);
			PopulateSectorPlane(s,1,s.ceilingplane);
		}
	}
}

#include "actors/fancy_floors.zsc"
#include "actors/fancy_ceilings.zsc"
#include "actors/fancy_walls.zsc"

Class SpawnEnvActorHandler : EventHandler
{
	// In the interests of neatness, make each piece of the puzzle a different
	// function that can be easily commented out for debugging's sake
	override void WorldLoaded(WorldEvent e)
	{
		SpawnFloorActors();
		SpawnFloorActors_OldWay();
		SpawnCeilingActors();
		SpawnWallActors();
	}
	
	// Spawn stuff on the floor the "old way" (in the center of every sector,
	// regardless of whether that center is actually in the sector or not.
	// only useful for things that are very likely gonna be a square.
	// Devised by Gutawer!
	void SpawnFloorActors_OldWay()
	{
		for (int i = 0; i < level.Sectors.Size(); i++)
		{
			let c = level.Sectors[i].centerspot;
			Actor.Spawn("FancyEnvActorFloorOldWay", (c.x, c.y, level.Sectors[i].floorplane.ZAtPoint(c)));
		}
	}
	
	// Spawn Stuff on the floor in a "grid" across all playable map space.
	// Thanks to Gutawer, PhantomBeta and _Bryan for helping debug this!
	void SpawnFloorActors()
    {
        //32704
		int spamx = -32448;
		int spamy = 32448;
		int spamz = 0;
		
		Vector2 spam2 = (spamx, spamy);
		Vector3 spam3 = (spamx, spamy, spamz);
		
		while (spamy > -32448)
		{
			while (spamx < 32448)
			{
				spamz = Sector.pointInSector((spamx, spamy)).floorplane.zAtPoint((spamx, spamy));
				if (level.IsPointInMap(spam3))
				{
					Actor.Spawn("FancyEnvActorFloor", (spamx, spamy, spamz));
				}
				spamx += 128;
				spam3 = (spamx, spamy, spamz);
			}
			spamx = -32448;
			spamy -= 128;
		}
    }
	
	// Spawn Stuff on the ceiling. Same method as with SpawnFloorActors, just at
	// a larger grid size for the sake of performance.
	void SpawnCeilingActors()
    {
        //32704
		int spamx = -32448;
		int spamy = 32448;
		int spamz = 0;
		
		Vector2 spam2 = (spamx, spamy);
		Vector3 spam3 = (spamx, spamy, spamz);
		
		while (spamy > -32448)
		{
			while (spamx < 32448)
			{
				spamz = Sector.pointInSector((spamx, spamy)).floorplane.zAtPoint((spamx, spamy));
				if (level.IsPointInMap(spam3))
				{
					Actor.Spawn("FancyEnvActorCeiling", (spamx, spamy, spamz));
				}
				spamx += 256;
				spam3 = (spamx, spamy, spamz);
			}
			spamx = -32448;
			spamy -= 256;
		}
    }
	
	// Spawn stuff on walls. Specifically, in the middle of appropriate linedefs.
	// Thanks Nash and Phantombeta!
	void SpawnWallActors()
	{
		for (int i = 0; i < level.Lines.Size(); i++)
		{			
			Line l = level.Lines[i];
			int spamf = 0;
			int spamc = 0;

			// do front first, then back
			for (int ii = 0; ii < 2; ii++)
			{
				double lineLen = l.delta.Length ();
				Vector2 spawnCoords = level.Vec2Offset (l.v1.p, l.delta.Unit () * (lineLen * 0.5));
				spamc = Sector.pointInSector(spawnCoords).ceilingplane.zAtPoint(spawnCoords);
				spamf = Sector.pointInSector(spawnCoords).floorplane.zAtPoint(spawnCoords);
				
				/*
				if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture("PLANET1", TexMan.Type_Any))
				Actor.Spawn("FancyWallTestSound", (spawnCoords,(spamc - 32)));
				
				if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture("COMPUTE2", TexMan.Type_Any))
				Actor.Spawn("FancyWallTestSound", (spawnCoords,(spamc - (spamf * 0.5))));
				
				if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture("STEP6", TexMan.Type_Any))
				Actor.Spawn("FancyWallTestSound", (spawnCoords,spamf));
				*/
				
				// Plutonia Waterfall
				string WallWaterfall[8];
				WallWaterfall[0] = "WFALL1";
				WallWaterfall[1] = "WFALL2";
				WallWaterfall[2] = "WFALL3";
				WallWaterfall[3] = "WFALL4";
				// for WADSMOOSH
				WallWaterfall[4] = "PWFALL1";
				WallWaterfall[5] = "PWFALL2";
				WallWaterfall[6] = "PWFALL3";
				WallWaterfall[7] = "PWFALL4";
				for (int i = 0; i < 8; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallWaterfall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallWaterfall", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallWaterfall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallWaterfall", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallWaterfall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallWaterfall", (spawnCoords,spamf));
				}
				
				// Bloodfall
				string WallBloodfall[4];
				WallBloodfall[0] = "BFALL1";
				WallBloodfall[1] = "BFALL2";
				WallBloodfall[2] = "BFALL3";
				WallBloodfall[3] = "BFALL4";
				for (int i = 0; i < 4; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallBloodfall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallBloodfall", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallBloodfall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallBloodfall", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallBloodfall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallBloodfall", (spawnCoords,spamf));
				}
				
				// Doom 2 Slimefall
				string WallSlimefall[4];
				WallSlimefall[0] = "SFALL1";
				WallSlimefall[1] = "SFALL2";
				WallSlimefall[2] = "SFALL3";
				WallSlimefall[3] = "SFALL4";
				for (int i = 0; i < 4; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallSlimefall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallSlimefall", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallSlimefall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallSlimefall", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallSlimefall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallSlimefall", (spawnCoords,spamf));
				}
				
				// Lavafalls
				string WallLavafall[12];
				// ObAddon Lavafall. Probably other lavafalls, too...
				WallLavafall[0] = "LFALL1";
				WallLavafall[1] = "LFALL2";
				WallLavafall[2] = "LFALL3";
				WallLavafall[3] = "LFALL4";
				WallLavafall[4] = "LFAL21";
				WallLavafall[5] = "LFAL22";
				WallLavafall[6] = "LFAL23";
				WallLavafall[7] = "LFAL24";
				// CC4 Tex
				WallLavafall[8] = "LAVFALL1";
				WallLavafall[9] = "LAVFALL2";
				WallLavafall[10] = "LAVFALL3";
				WallLavafall[11] = "LAVFALL4";
				for (int i = 0; i < 12; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallLavafall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallLavafall", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallLavafall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallLavafall", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallLavafall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallLavafall", (spawnCoords,spamf));
				}
				
				
				// Doom 1 Slimedrip
				string WallSlimedrip[3];
				WallSlimedrip[0] = "SLADRIP1";
				WallSlimedrip[1] = "SLADRIP2";
				WallSlimedrip[2] = "SLADRIP3";
				for (int i = 0; i < 3; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallSlimedrip[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallSlimedrip", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallSlimedrip[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallSlimedrip", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallSlimedrip[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallSlimedrip", (spawnCoords,spamf));
				}
				
				// Gargoyle Blood Fountain
				string WallGargfont[3];
				WallGargfont[0] = "GSTFONT1";
				WallGargfont[1] = "GSTFONT2";
				WallGargfont[2] = "GSTFONT3";
				for (int i = 0; i < 3; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallGargfont[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallGargfont", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallGargfont[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallGargfont", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallGargfont[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallGargfont", (spawnCoords,spamf));
				}
				
				// Compstation
				string WallCompstation[7];
				WallCompstation[0] = "COMPSTA1";
				WallCompstation[1] = "COMPSTA2";
				// CC4 Tex
				WallCompstation[2] = "COMPSTA3";
				WallCompstation[3] = "COMPSTA4";
				WallCompstation[4] = "COMPSTA5";
				WallCompstation[5] = "COMPSTA6";
				WallCompstation[6] = "COMPTALR";
				for (int i = 0; i < 7; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallCompstation[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallCompstation", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallCompstation[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallCompstation", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallCompstation[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallCompstation", (spawnCoords,spamf));
				}
				
				// Fireblu
				string WallFireblu[2];
				WallFireblu[0] = "FIREBLU1";
				WallFireblu[1] = "FIREBLU2";
				for (int i = 0; i < 2; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallFireblu[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallFireblu", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallFireblu[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallFireblu", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallFireblu[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallFireblu", (spawnCoords,spamf));
				}
				
				// Firey Walls
				string WallFirewall[9];
				WallFirewall[0] = "FIREMAG1";
				WallFirewall[1] = "FIREMAG2";
				WallFirewall[2] = "FIREMAG3";
				WallFirewall[3] = "FIREWALL";
				WallFirewall[4] = "FIREWALA";
				WallFirewall[5] = "FIREWALB";
				WallFirewall[6] = "FIRELAVA";
				WallFirewall[7] = "FIRELAV2";
				WallFirewall[8] = "FIRELAV3";
				for (int i = 0; i < 9; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallFirewall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallFirewall", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallFirewall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallFirewall", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallFirewall[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallFirewall", (spawnCoords,spamf));
				}
				
				// Generic Hummy Tech
				string WallTechhum[9];
				WallTechhum[0] = "COMPTALL";
				WallTechhum[1] = "COMP2";
				WallTechhum[2] = "SPACEW3";
				WallTechhum[3] = "COMPUTE1";
				WallTechhum[4] = "PLANET1";
				// CC4 Tex
				WallTechhum[5] = "COMPUTE4";
				WallTechhum[6] = "COMPUTE7";
				WallTechhum[7] = "COMPUTE8";
				WallTechhum[8] = "COMPUTE9";
				for (int i = 0; i < 9; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallTechhum[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallTechhum", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallTechhum[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallTechhum", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallTechhum[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallTechhum", (spawnCoords,spamf));
				}
				
				// Wall-Based Lighting
				string WallLights[18];
				WallLights[0] = "LITE3";
				WallLights[1] = "LITE5";
				WallLights[2] = "LITEBLU1";
				WallLights[3] = "LITEBLU4";
				WallLights[4] = "BRICKLIT";
				WallLights[5] = "BSTONE3";
				WallLights[6] = "LITE2";
				WallLights[7] = "LITE96";
				WallLights[8] = "LITEMET";
				WallLights[9] = "LITERED";
				WallLights[10] = "LITESTON";
				WallLights[11] = "LITE4";
				WallLights[12] = "LITEGRN1";
				WallLights[13] = "LITERED1";
				WallLights[14] = "LITERED2";
				WallLights[15] = "LITEYEL1";
				WallLights[16] = "LITEYEL2";
				WallLights[17] = "LITEYEL3";
				for (int i = 0; i < 18; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallLights[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallLights", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallLights[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallLights", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallLights[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallLights", (spawnCoords,spamf));
				}
				
				// CCTEX4/ObAddon Static Monitor
				string WallStatic[4];
				WallStatic[0] = "COMPFUZ1";
				WallStatic[1] = "COMPFUZ2";
				WallStatic[2] = "COMPFUZ3";
				WallStatic[3] = "COMPFUZ4";
				for (int i = 0; i < 4; i++)
				{
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture(WallStatic[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallStatic", (spawnCoords,(spamc - 32)));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture(WallStatic[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallStatic", (spawnCoords,(spamc - (spamf * 0.5))));
					if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture(WallStatic[i], TexMan.Type_Any))
					Actor.Spawn("FancyWallStatic", (spawnCoords,spamf));
				}
				
				// One-Offs
				// Creepy Face Texture
				if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.top) == TexMan.CheckForTexture("SP_FACE1", TexMan.Type_Any))
				Actor.Spawn("FancyWallFaces", (spawnCoords,(spamc - 32)));
				if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.mid) == TexMan.CheckForTexture("SP_FACE1", TexMan.Type_Any))
				Actor.Spawn("FancyWallFaces", (spawnCoords,(spamc - (spamf * 0.5))));
				if (l.sidedef[ii] && l.sidedef[ii].GetTexture(Side.bottom) == TexMan.CheckForTexture("SP_FACE1", TexMan.Type_Any))
				Actor.Spawn("FancyWallFaces", (spawnCoords,spamf));
			}
		}
	}
}

class FancyEnvActorFloor : Actor
{
	Default
	{
		-SOLID
		+DONTSPLASH
		+NOTELEPORT
		+NOCLIP
		+NOBLOCKMAP
		RenderStyle "None";
		radius 1;
		height 1;
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			// this is marginally less dumb than last time
			
			// Nukage
			string FloorNukage[4];
			FloorNukage[0] = "NUKAGE1";
			FloorNukage[1] = "NUKAGE2";
			FloorNukage[2] = "NUKAGE3";
			FloorNukage[3] = "NUKAGE4";

			for (int i = 0; i < 4; i++)
			{
				if (floorpic == TexMan.CheckForTexture(FloorNukage[i], TexMan.Type_Any))
				{
					if (!CountProximity ("FancySectorNukageCore", 256))
					{
						A_SpawnItem("FancySectorNukageCore");
					}
					A_SpawnItem("FancySectorNukage");		
				}
			}
			
			// Water
			string FloorWater[4];
			FloorWater[0] = "FWATER1";
			FloorWater[1] = "FWATER2";
			FloorWater[2] = "FWATER3";
			FloorWater[3] = "FWATER4";
			for (int i = 0; i < 4; i++)
			{
				if (floorpic == TexMan.CheckForTexture(FloorWater[i], TexMan.Type_Any))
					A_SpawnItem("FancySectorWaterCore");			
			}
			
			// Slime
			string FloorSlime[12];
			FloorSlime[0] = "SLIME01";
			FloorSlime[1] = "SLIME02";
			FloorSlime[2] = "SLIME03";
			FloorSlime[3] = "SLIME04";
			FloorSlime[4] = "SLIME05";
			FloorSlime[5] = "SLIME06";
			FloorSlime[6] = "SLIME07";
			FloorSlime[7] = "SLIME08";
			// ObAddon black oil sludge
			FloorSlime[8] = "SLUDGE01";
			FloorSlime[9] = "SLUDGE02";
			FloorSlime[10] = "SLUDGE03";
			FloorSlime[11] = "SLUDGE04";
			for (int i = 0; i < 12; i++)
			{
				if (floorpic == TexMan.CheckForTexture(FloorSlime[i], TexMan.Type_Any))
					A_SpawnItem("FancySectorSlimeCore");			
			}
				
			// Lava
			string FloorLava[8];
			FloorLava[0] = "LAVA1";
			FloorLava[1] = "LAVA2";
			FloorLava[2] = "LAVA3";
			FloorLava[3] = "LAVA4";
			// ObAddon Quake Lava
			FloorLava[4] = "QLAVA1";
			FloorLava[5] = "QLAVA2";
			FloorLava[6] = "QLAVA3";
			FloorLava[7] = "QLAVA4";
			for (int i = 0; i < 8; i++)
			{
				if (floorpic == TexMan.CheckForTexture(FloorLava[i], TexMan.Type_Any))
				{
					
					if (!CountProximity ("FancySectorLavaCore", 256))
					{
						A_SpawnItem("FancySectorLavaCore");
					}
					A_SpawnItem("FancySectorLava");
				}		
			}
				
			// Blood
			string FloorBlood[4];
			FloorBlood[0] = "BLOOD1";
			FloorBlood[1] = "BLOOD2";
			FloorBlood[2] = "BLOOD3";
			FloorBlood[3] = "BLOOD4";
			for (int i = 0; i < 4; i++)
			{
				if (floorpic == TexMan.CheckForTexture(FloorBlood[i], TexMan.Type_Any))
					A_SpawnItem("FancySectorSlimeCore");			
			}
				
			// Hot
			string FloorHot[4];
			FloorHot[0] = "SLIME09";
			FloorHot[1] = "SLIME10";
			FloorHot[2] = "SLIME11";
			FloorHot[3] = "SLIME12";
			for (int i = 0; i < 4; i++)
			{
				if (floorpic == TexMan.CheckForTexture(FloorHot[i], TexMan.Type_Any))
					A_SpawnItem("FancySectorHotCore");			
			}
			
			// XWATER from ObAddon
			string FloorXWater[4];
			FloorXWater[0] = "XWATER1";
			FloorXWater[1] = "XWATER2";
			FloorXWater[2] = "XWATER3";
			FloorXWater[3] = "XWATER4";
			for (int i = 0; i < 4; i++)
			{
				if (floorpic == TexMan.CheckForTexture(FloorXWater[i], TexMan.Type_Any))
					A_SpawnItem("FancySectorXWaterCore");			
			}
		}
		Stop;
	Remove:
		TNT1 A 0;
		stop;
	}
}

class FancyEnvActorFloorOldWay : Actor
{
	Default
	{
		-SOLID
		+DONTSPLASH
		+NOTELEPORT
		+NOCLIP
		+NOBLOCKMAP
		RenderStyle "None";
		radius 1;
		height 1;
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			// Floor Teleporter
			string FloorTeleporter[10];
			FloorTeleporter[0] = "GATE1";
			FloorTeleporter[1] = "GATE2";
			FloorTeleporter[2] = "GATE3";
			FloorTeleporter[3] = "GATE4";
			// CC4 Tex
			FloorTeleporter[4] = "GATE3TN";
			FloorTeleporter[5] = "GATE4BL";
			FloorTeleporter[6] = "GATE4GN";
			FloorTeleporter[7] = "GATE4OR";
			FloorTeleporter[8] = "GATE4RD";
			FloorTeleporter[9] = "GATE4YL";
			for (int i = 0; i < 10; i++)
			{
				if (floorpic == TexMan.CheckForTexture(FloorTeleporter[i], TexMan.Type_Any))
					A_SpawnItem("FancySectorTeleporterCore");			
			}
		}
		Stop;
	Remove:
		TNT1 A 0;
		stop;
	}
}

class FancyEnvActorCeiling : Actor
{
	Default
	{
		-SOLID
		+DONTSPLASH
		+NOTELEPORT
		+NOCLIP
		+NOBLOCKMAP
		RenderStyle "None";
		radius 1;
		height 1;
	}
	
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0
		{
			// back to the dumb ways
			if (ceilingpic == TexMan.CheckForTexture("F_SKY1", TexMan.Type_Any))
				A_SpawnItem("FancySectorSky");	
				
			// Generic Ceiling Lights
			string CeilingLights[10];
			CeilingLights[0] = "CEIL1_2";
			CeilingLights[1] = "CEIL1_3";
			CeilingLights[2] = "CEIL3_6";
			CeilingLights[3] = "FLAT2";
			CeilingLights[4] = "FLAT17";
			CeilingLights[5] = "GRNLITE1";
			CeilingLights[6] = "TLITE6_1";
			CeilingLights[7] = "TLITE6_4";
			CeilingLights[8] = "TLITE6_5";
			CeilingLights[9] = "TLITE6_6";
			for (int i = 0; i < 10; i++)
			{
				if (ceilingpic == TexMan.CheckForTexture(CeilingLights[i], TexMan.Type_Any))
					A_SpawnItem("FancySectorCeilingLite");			
			}
		}
		Stop;
	}
}

Class VisualSpecialEffect : ACTOR
{
	Default
	{
	  +CLIENTSIDEONLY
	  +NOGRAVITY
	  +NOINTERACTION
	  +NOBLOCKMAP
	  +NOTELEPORT
	  +ROLLSPRITE
	  +FORCEXYBILLBOARD
	  +NOCLIP
	  +DONTSPLASH
	  Renderstyle "Add";
	}
}

Class BouncyPhysicalThing : ACTOR
{
	Default
	{
	  +ROLLSPRITE
	  +DOOMBOUNCE
	  +FORCEXYBILLBOARD
	  +CLIENTSIDEONLY
	  +NOTELEPORT
	  +PAINLESS
	  +ALLOWBOUNCEONACTORS
	  +MISSILE
	  -NOGRAVITY
	  -CANBOUNCEWATER
	  -NOINTERACTION
	  Renderstyle "translucent";
	  Speed 0.01;
	  BounceType "Doom";
	  BounceCount 4;
	  Gravity 0.85;
	  Health 1;
	  Radius 1;
	  Height 2;
	  Mass 1;
	}
}


Class LiquidParticle : BouncyPhysicalThing
{
	Default
	{
		+NOTRIGGER
		+EXPLODEONWATER
		+DONTSPLASH
		+CANNOTPUSH
		+ALLOWTHRUFLAGS
		+THRUACTORS
		-NOGRAVITY
		-SKYEXPLODE
		-NOINTERACTION
		-BRIGHT
		BounceCount 1;
		BounceFACTOR 0.25;
		Friction 0.85;
		Renderstyle "translucent";
		Radius 2;
		Height 4;
		Speed 3;
		Damage 0;
		Alpha 0.92;
		Scale 0.85;
		Mass 3;
		Gravity 1.08;
	}

	States
	{
		Spawn:
			LQP0 A 0 NoDelay;
			LQP0 A 0 A_SetScale(0.01 * random(55,99));
			TNT1 A 0 A_Jump(255,"Spawn1", "Spawn2");
		Spawn1:
			LQP0 AAAAAAAAAA 1 A_SpawnItemEx("LiquidParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 AAAAAAAAAA 1 A_SpawnItemEx("LiquidParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 AAAAAAAAAA 1 A_SpawnItemEx("LiquidParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 AAAAAAAAAA 1 A_FadeOut(0.1);
			Stop;
		Spawn2:
			LQP0 AAAAAA 1 A_SpawnItemEx("LiquidParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 B 1;
			LQP0 CD 1;
			Stop;
		Crash:
			LQP0 B 1;
			LQP0 CD 1;
			Stop;
		Death:
			LQP0 B 1;
			LQP0 CD 1;
			Stop;
	}
}

Class LiquidParticleTrail : VisualSpecialEffect
{
	Default
	{
		+PAINLESS
		+MISSILE
		+NOTRIGGER
		+THRUACTORS
		+EXPLODEONWATER
		+NOCLIP
		-NOGRAVITY
		-NOINTERACTION
		-SKYEXPLODE
		-BRIGHT
		Renderstyle "translucent";
		Speed 3;
		Damage 0;
		Alpha 0.92;
		Scale 0.66;
		Mass 2;
		Gravity 1;
	}
	States
	{
		Spawn:
			LQP0 A 0 NoDelay;
			LQP0 AAAAA 1 A_FadeOut(0.1);
			LQP0 AAAAA 1 A_FadeOut(0.1);
			Stop;
		Crash:
			LQP0 BCD 1;
			Stop;
		Death:
			LQP0 BCD 1;
			Stop;
	}
}

Class SlimeParticle : BouncyPhysicalThing
{
	Default
	{
		+NOTRIGGER
		+EXPLODEONWATER
		+DONTSPLASH
		+CANNOTPUSH
		+ALLOWTHRUFLAGS
		+THRUACTORS
		-NOGRAVITY
		-SKYEXPLODE
		-NOINTERACTION
		-BRIGHT
		BounceCount 1;
		BounceFACTOR 0.25;
		Friction 0.85;
		Renderstyle "translucent";
		Radius 2;
		Height 4;
		Speed 3;
		Damage 0;
		Alpha 0.92;
		Scale 0.85;
		Mass 3;
		Gravity 1.16;
	}

	States
	{
		Spawn:
			LQP0 A 0 NoDelay;
			LQP0 A 0 A_SetScale(0.01 * random(88,133));
			TNT1 A 0 A_Jump(255,"Spawn1", "Spawn2");
		Spawn1:
			LQP0 AAAAAAAAAA 1 A_SpawnItemEx("SlimeParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 AAAAAAAAAA 1 A_SpawnItemEx("SlimeParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 AAAAAAAAAA 1 A_SpawnItemEx("SlimeParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 AAAAAAAAAA 1 A_FadeOut(0.1);
			Stop;
		Spawn2:
			LQP0 A 0 A_SetScale(-Scale.X);
			LQP0 AAAAAAAAAA 1 A_SpawnItemEx("SlimeParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 AAAAAAAAAA 1 A_SpawnItemEx("SlimeParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 AAAAAAAAAA 1 A_SpawnItemEx("SlimeParticleTrail", flags: SXF_TRANSFERTRANSLATION);
			LQP0 AAAAAAAAAA 1 A_FadeOut(0.1);
			Stop;
		Crash:
			LQP0 BBBBBBBBBB 2 A_SetScale(scale.X * 1.1, scale.Y * 0.9);
			LQP0 BBBBBBBBBB 1;
			LQP0 BBBBBBBBBB 2 A_FadeOut(0.1);
			Stop;
		Death:
			LQP0 BBBBBBBBBB 2 A_SetScale(scale.X * 1.1, scale.Y * 0.9);
			LQP0 BBBBBBBBBB 1;
			LQP0 BBBBBBBBBB 2 A_FadeOut(0.1);
			Stop;
	}
}

Class SlimeParticleTrail : VisualSpecialEffect
{
	Default
	{
		+PAINLESS
		+MISSILE
		+NOTRIGGER
		+THRUACTORS
		+EXPLODEONWATER
		+NOCLIP
		-NOGRAVITY
		-NOINTERACTION
		-SKYEXPLODE
		-BRIGHT
		Renderstyle "translucent";
		Speed 3;
		Damage 0;
		Alpha 0.92;
		Scale 0.92;
		Mass 2;
		Gravity 0.91;
	}
	States
	{
		Spawn:
			LQP0 A 0 NoDelay;
			LQP0 AAAAA 1;
			LQP0 AAAAA 1 A_FadeOut(0.2);
			Stop;
		Crash:
			LQP0 BCD 1;
			Stop;
		Death:
			LQP0 BCD 1;
			Stop;
	}
}


//========================================================================
//====== BLOOD ===========================================================
//========================================================================

class WaterBloodSplat : Blood
{
	Default
	{
		-NOINTERACTION
		+NOTELEPORT
		+NOCLIP
		+ClientSideOnly
		+RollSprite
		+MoveWithSector
		+NOBLOCKMAP
		+FLATSPRITE
		-NOGRAVITY
		+NOTONAUTOMAP
		+THRUACTORS
		+DONTSPLASH
		Height 2;
		Radius 16;
		Alpha 0.95;
		Gravity 4;
		Scale 1;
		MaxStepHeight 1;
		MaxDropOffHeight 12;
		FloatBobPhase 0;
		Friction 0.01;
	}
	States
	{
	 Spawn:
		BLDS E 0 A_SetRoll(random(1,359));
		BLDS E 0 A_SetScale(0.02);
		BLDS EE 1
			{
				A_SetRoll(roll + 0.5);
				A_SetScale(scale.x * 1.08);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEE 3
			{
				A_FadeOut(0.01);
				A_SetRoll(roll + 1);
				A_SetScale(scale.x * 1.06);
			}
		BLDS EEEEEEEEEEEEEEEEEEEE 3
			{
				A_FadeOut(0.005);
				A_SetRoll(roll + 0.9);
				A_SetScale(scale.x * 1.05);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 3
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.8);
				A_SetScale(scale.x * 1.04);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 3
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.7);
				A_SetScale(scale.x * 1.02);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 3
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.6);
				A_SetScale(scale.x * 1.007);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 3
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.6);
				A_SetScale(scale.x * 1.005);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 5
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.5);
				A_SetScale(scale.x * 1.005);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 9
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.5);
				A_SetScale(scale.x * 1.004);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 9
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.5);
				A_SetScale(scale.x * 1.003);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 9
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.5);
				A_SetScale(scale.x * 1.002);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 9
			{
				A_FadeOut(0.05);
				A_SetRoll(roll + 0.4);
				A_SetScale(scale.x * 1.001);
			}
		Stop;
	}
}
	 
class SlimeBloodSplat : WaterBloodSplat
{
	States
	{
	 Spawn:
		BLDS E 0 A_SetRoll(random(1,359));
		BLDS E 0 A_SetScale(0.02);
		BLDS EE 1
			{
				A_SetRoll(roll + 0.3);
				A_SetScale(scale.x * 1.04);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.01);
				A_SetRoll(roll + 0.3);
				A_SetScale(scale.x * 1.02);
			}
		BLDS EEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.005);
				A_SetRoll(roll + 0.3);
				A_SetScale(scale.x * 1.03);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.2);
				A_SetScale(scale.x * 1.04);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.2);
				A_SetScale(scale.x * 1.02);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.2);
				A_SetScale(scale.x * 1.003);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.2);
				A_SetScale(scale.x * 1.002);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.15);
				A_SetScale(scale.x * 1.002);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.15);
				A_SetScale(scale.x * 1.001);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.15);
				A_SetScale(scale.x * 1.001);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.15);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.05);
				A_SetRoll(roll + 0.15);
			}
		Stop;
	}
}
	 
class LavaBloodSplat : SlimeBloodSplat
{
	States
	{
	 Spawn:
		BLDS E 0 A_SetRoll(random(1,359));
		BLDS E 0 A_SetScale(0.02);
		BLDS EE 1
			{
				A_SetRoll(roll + 0.2);
				A_SetScale(scale.x * 1.04);
				A_SpawnItemEx("FlameSmoke");
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.01);
				A_SetRoll(roll + 0.2);
				A_SetScale(scale.x * 1.03);
				A_SpawnItemEx("FlameSmoke");
			}
		BLDS EEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.02);
				A_SetRoll(roll + 0.2);
				A_SetScale(scale.x * 1.03);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.05);
				A_SetRoll(roll + 0.1);
				A_SetScale(scale.x * 1.02);
			}
		BLDS EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.1);
				A_SetScale(scale.x * 1.01);
			}
		Stop;
	}
}

//========================================================================
//====== SMOKE ===========================================================
//========================================================================


Class Smoke : VisualSpecialEffect
{
	Default
	{
		Radius 0;
		Height 0;
		RenderStyle "Shaded";
		StencilColor "44 44 44";
		Alpha 0.06;
		Scale 0.25;
		Gravity -0.12;
		Speed 0.25;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(255,"Spawn1", "Spawn2");
		Spawn1:
			SMOK C 2 A_SetRoll(roll + random(-359,359));
			SMOK CCCC random(1,3)
				{
					A_FadeIn(0.05);
					A_SetRoll(roll + 3);
					A_SetScale(scale.x * 1.35);
				}
			SMOK CCCCCCCCCCCCCCCCCCCCC random(1,3)
				{
					A_FadeOut(0.015);
					A_SetRoll(roll + 3);
					A_SetScale(scale.x * 1.05);
				}
			SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(1,3)
				{
					A_FadeOut(0.006);
					A_SetRoll(roll + 2);
					A_SetScale(scale.x * 1.02);
				}
		Fadeout:
			SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(1,3)
				{
					A_FadeOut(0.0005);
					A_SetRoll(roll + 1);
					A_SetScale(scale.x * 1.01);
				}
			Loop;
		Spawn2:
			SMOK C 2 A_SetRoll(roll + random(-359,359));
			SMOK CCCC random(1,3)
				{
					A_FadeIn(0.05);
					A_SetRoll(roll - 3);
					A_SetScale(scale.x * 1.35);
				}
			SMOK CCCCCCCCCCCCCCCCCCCCC random(1,3)
				{
					A_FadeOut(0.015);
					A_SetRoll(roll - 3);
					A_SetScale(scale.x * 1.05);
				}
			SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(1,3)
				{
					A_FadeOut(0.006);
					A_SetRoll(roll - 2);
					A_SetScale(scale.x * 1.02);
				}
		Fadeout:
			SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(1,3)
				{
					A_FadeOut(0.0005);
					A_SetRoll(roll - 1);
					A_SetScale(scale.x * 1.01);
				}
			Loop;
	}
}


Class SlowSmoke : Smoke
{
	States
	{
	Spawn:
		TNT1 A 0 A_SetRoll(random(1,359));
		SMOK CCCC random(2,5)
			{
				A_FadeIn(0.05);
				A_SetRoll(roll + 2);
				A_SetScale(scale.x * 1.3);
			}
		SMOK CCCCCCCCCCCCCCCCCCCCC random(3,6)
			{
				A_FadeOut(0.02);
				A_SetRoll(roll + 1);
				A_SetScale(scale.x * 1.05);
			}
		SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(3,6)
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.5);
				A_SetScale(scale.x * 1.02);
			}
	Fadeout:
		SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(3,6)
			{
				A_FadeOut(0.001);
				A_SetRoll(roll + 0.2);
				A_SetScale(scale.x * 1.01);
			}
		Loop;
	}
}


Class FastSmoke : Smoke
{
	States
	{
	Spawn:
		TNT1 A 0 A_SetRoll(random(1,359));
		SMOK CCCC 1
			{
				A_FadeIn(0.05);
				A_SetRoll(roll + 2);
				A_SetScale(scale.x * 1.3);
			}
		SMOK CCCCCCCCCCCCCCCCCCCCC 1
			{
				A_FadeOut(0.02);
				A_SetRoll(roll + 1);
				A_SetScale(scale.x * 1.05);
			}
		SMOK CCCCCCCCCCCCCCCCCCCCCCCCC 1
			{
				A_FadeOut(0.002);
				A_SetRoll(roll + 0.5);
				A_SetScale(scale.x * 1.02);
			}
	Fadeout:
		SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1
			{
				A_FadeOut(0.001);
				A_SetRoll(roll + 0.2);
				A_SetScale(scale.x * 1.01);
			}
		Loop;
	}
}

Class BigSmoke : Smoke
{
	Default
	{
		Scale 0.60;
	}
}

Class BigSlowSmoke : SlowSmoke
{
	Default
	{
		Scale 0.60;
	}
}

Class BigFastSmoke : FastSmoke
{
	Default
	{
		Scale 0.60;
	}
}

Class SmallSmoke : Smoke
{
	Default
	{
		Scale 0.06;
	}
}

Class FlameSmoke : SmallSmoke
{
	Default
	{
		RenderStyle "Shaded";
		StencilColor "32 32 32";
		Alpha 0.15;
	}
}


Class BloodMist : Smoke
{
	Default
	{
		RenderStyle "Shaded";
		StencilColor "55 11 11";
		Alpha 0.18;
		Scale 0.08;
	}
}

Class SmallSlowSmoke : SlowSmoke
{
	Default
	{
		Scale 0.06;
	}
}

Class SmallFastSmoke : FastSmoke
{
	Default
	{
		Scale 0.06;
	}
}

Class TinySmoke : Smoke
{
	Default
	{
		Scale 0.02;
	}
}

Class TinySlowSmoke : SlowSmoke
{
	Default
	{
		Scale 0.02;
	}
}

Class TinyFastSmoke : FastSmoke
{
	Default
	{
		Scale 0.02;
	}
}
	



Class StillSmoke : VisualSpecialEffect
{
	Default
	{
		Radius 0;
		Height 0;
		Scale 2;
		RenderStyle "Shaded";
		StencilColor "55 55 55";
		Alpha 0.16;
	}
	States
	{
	Spawn:
		SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(1,3)
			{
				A_FadeIn(0.005);
				A_SetRoll(roll + 0.1);
				A_SetScale(scale.x * 1.005);
			}
		SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(1,3)
			{
				A_FadeOut(0.001);
				A_SetRoll(roll + 0.1);
				A_SetScale(scale.x * 1.002);
			}
		SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(1,3)
			{
				A_FadeIn(0.001);
				A_SetRoll(roll + 0.1);
				A_SetScale(scale.x * 0.998);
			}
	Fadeout:
		SMOK CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC random(1,3)
			{
				A_FadeOut(0.005);
				A_SetRoll(roll + 0.1);
				A_SetScale(scale.x * 1.001);
			}
		Loop;
	}
}