// Test Actor
class FancyWallTestSound : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallTestSound", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/test", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/test", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Plutonia Waterfalls
class FancyWallWaterfall : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallWaterfall", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/waterfall", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/waterfall", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Bloodfalls
class FancyWallBloodfall : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallBloodfall", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/bloodfall", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/bloodfall", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Doom 2 Slimefalls
class FancyWallSlimefall : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallSlimefall", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/slimefall", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/slimefall", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// ObAddon (and prob. others) Lavafalls
class FancyWallLavafall : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallLavafall", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/lavafall", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/lavafall", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Doom 1 slime dripping out of a drain
class FancyWallSlimedrip : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallSlimedrip", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/slimedrip", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/slimedrip", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Gargoyle-head blood fountain
class FancyWallGargfont : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallGargfont", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/slimedrip", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/slimedrip", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// COMPSTA Wall Computers
class FancyWallCompstation : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallCompstation", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/compstation", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/compstation", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Flaming Walls
class FancyWallFirewall : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallFirewall", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/firewall", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/firewall", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// The Battler-Prince
class FancyWallFireblu : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallFireblu", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/fireblu", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/fireblu", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Creepy Faces on the Wall
class FancyWallFaces : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallFaces", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/faces", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/faces", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Tech Humming
class FancyWallTechhum : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallTechhum", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/techhum", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/techhum", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Lights on the Wall
class FancyWallLights : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallLights", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/walllight", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/walllight", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}

// Static Monitor
class FancyWallStatic : Actor
{
	Default
	{
		-SOLID
		-NOCLIP
		+DONTSPLASH
		+NOTELEPORT
		+NOINTERACTION
		+NOBLOCKMAP
		+CLIENTSIDEONLY
		+MOVEWITHSECTOR
		radius 1;
		height 1;
		RenderStyle "None";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SetTics(random(1,8));
			TNT1 A 0
			{
				if (CountProximity ("FancyWallStatic", 16, CPXF_NOZ))
				{
					return ResolveState("Null");
				} else {
					return ResolveState(null);
				}
			}
			TNT1 A 0 A_PlaySound("world/static", CHAN_BODY, 1.0, 1);
		Live:
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 35;
			goto Live;
		Far:
			TNT1 A 0 A_StopSound(CHAN_BODY);
			TNT1 A 35;
			TNT1 A 0 A_CheckRange(1024, "Far", 1);
			TNT1 A 0 A_PlaySound("world/static", CHAN_BODY, 1.0, 1);
			goto Live;
	}
}