//===========================================================================
//
// CHEELLO VOXEL DOOM
//
// ZScript code: Copyright (C) 2022 Nash Muhandes
//
// License: MIT
//
//===========================================================================

//===========================================================================
//
// Megasphere
//
//===========================================================================

class CheelloMegasphere : Megasphere replaces Megasphere
{
	override void PostBeginPlay(void)
	{
		Super.PostBeginPlay();
		CheelloSphereShell.SpawnShell(self);
	}
}

//===========================================================================
//
// CheelloMegasphereShell
//
//===========================================================================

class CheelloMegasphereShell : CheelloSphereShell
{
	States
	{
	Spawn:
		MEGA E -1;
		Stop;
	}
}
