//===========================================================================
//
// DDS VOXEL GORE HELPERS
//
//===========================================================================

//===========================================================================
//
// DDSRAVoxHandler
// General helper functionality for voxel-gore angle alignment.
//
//===========================================================================

class DDSRAVoxHandler : EventHandler
{
	override void WorldThingDied(WorldEvent e)
	{
		// Make monsters face the player who killed them.
		if (e.Thing && e.Thing.bIsMonster && e.Thing.Target && e.Thing.Target is "PlayerPawn")
			e.Thing.Angle = e.Thing.AngleTo(e.Thing.Target);
	}
}
