#library "fog"
#include "zcommon.acs"

Script 1128 Enter { ACS_ExecuteAlways(1129,0); }

Script 1129 (void)
{

	int local0 = 0;
	int fogdensity = GetUserCVAR(0, "udv_fogdensity");
	int fograndom = GetUserCVAR(0, "udv_fograndom");
	int fogcolor = GetUserCVAR(0, "udv_fogcolor");
	int getred;
	int getgreen;
	int getblue;
	
	If(fogcolor)
	{
		getred = random(0,60);
		getgreen = random(0,60);
		getblue = random(0,60);
		SetUserCVAR(0, "udv_getred", getred);
		SetUserCVAR(0, "udv_getgreen", getgreen);
		SetUserCVAR(0, "udv_getblue", getblue);
	}
	Else
	{
		getred = GetUserCVAR(0, "udv_getred");
		getgreen = GetUserCVAR(0, "udv_getgreen");
		getblue = GetUserCVAR(0, "udv_getblue");
	}
	
	If(GetUserCVAR(0, "udv_togglefog"))
	{
		If(fogdensity > 0 && !fograndom )//If(getusercvar(0,"udv_togglefog"))
		{
				Until(local0 > 49999) {
					Sector_SetFade(local0, getred, getgreen, getblue);
					local0++;
				}
				SetGlobalFogParameter(0, 64*fogdensity);//256);
				SetGlobalFogParameter(1, 32*fogdensity);//128);
				SetGlobalFogParameter(2, 32*fogdensity);//128);
		}
		Else If(fogdensity > 0 && fograndom )
		{
			int fog1 = random(0, fogdensity);
			int fog2 = random(0, fogdensity);
			int fog3 = random(0, fogdensity);
			
				Until(local0 > 49999) {
					Sector_SetFade(local0, getred, getgreen, getblue);
					local0++;
				}
				SetGlobalFogParameter(0, 64*fog1);//256);
				SetGlobalFogParameter(1, 32*fog2);//128);
				SetGlobalFogParameter(2, 32*fog3);//128);
		}
		Else
		{
				Until(local0 > 49999) {
					Sector_SetFade(local0, 0, 0, 0);
					local0++;
				}
				SetGlobalFogParameter(0, 0);
				SetGlobalFogParameter(1, 0);
				SetGlobalFogParameter(2, 0);
		}
	}
}
